#!/bin/bash 
# -*-indent-tabs-mode:t;c-basic-offset:4;tab-width:4;autowrap:nil;-*-

(mkdir -p build.g++.debug    && cd build.g++.debug    && CXX=g++                                 cmake .. -DCMAKE_BUILD_TYPE=Debug     && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.g++.codecov  && cd build.g++.codecov  && CXX=g++ CXXFLAGS="-coverage"            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-coverage -lgcov"   && make -j 12 && ctest -j 12 --output-on-failure -T Test -T Coverage) || exit
(mkdir -p build.g++          && cd build.g++          && CXX=g++                                 cmake ..                              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.g++.memchk   && cd build.g++.memchk   && CXX=g++                                 cmake ..                              && make -j 12 && ctest -T memcheck -j 12 --output-on-failure) || exit
(mkdir -p build.g++-8        && cd build.g++-8        && CXX=g++-8                               cmake ..                              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.g++-std17    && cd build.g++-std17    && CXX=g++                                 cmake .. -DCMAKE_CXX_STANDARD=17      && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.clang++      && cd build.clang++      && CXX=clang++                             cmake ..                              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.g++.asan     && cd build.g++.asan     && CXX=g++      CXXFLAGS="-fsanitize=address"                      cmake .. -D CMAKE_BUILD_TYPE=Debug && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.clang++.asan && cd build.clang++.asan && CXX=clang++  CXXFLAGS="-fsanitize=undefined -fsanitize=address" cmake .. -D CMAKE_BUILD_TYPE=Debug && make -j 12 && ASAN_OPTIONS="halt_on_error=1 detect_leaks=1" ctest -j 12 --output-on-failure) || exit
#(mkdir -p build.clang++-11  && cd build.clang++-11  && CXX=clang++-11                          cmake ..                              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.nvcc         && cd build.nvcc         && CUDACXX="/usr/local/cuda-11.0/bin/nvcc" cmake .. -DENABLE_CUDA=1              && make -j 10 && ctest -j 10 --output-on-failure) || exit
(mkdir -p build.nvcc-11.1    && cd build.nvcc-11.1    && CUDACXX="/usr/local/cuda-11.1/bin/nvcc" cmake .. -DENABLE_CUDA=1              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.icpc-nomkl   && cd build.icpc-nomkl   && CXX="/opt/intel/sw_dev_tools/bin/icpc"  cmake ..                              && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.g++cppcheck  && cd build.g++cppcheck  && CXX=g++                                 cmake .. -DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--inline-suppr;--suppress=*:*thrust/complex*;--suppress=missingInclude;--suppress=unmatchedSuppression;--suppress=preprocessorErrorDirective;--language=c++;--std=c++14;--error-exitcode=66" && make -j 12 && ctest -j 12 --output-on-failure) || exit
(mkdir -p build.clang++.tidy && cd build.clang++.tidy && CXX=clang++                             cmake .. -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*,-fuchsia-default-arguments-calls,-fuchsia-statically-constructed-objects,-fuchsia-overloaded-operator,-cppcoreguidelines-pro-type-vararg,-hicpp-vararg,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-cppcoreguidelines-macro-usage,-cert-err58-cpp;--warnings-as-errors=*"  && make -j 12 && ctest -j 12 --output-on-failure) || exit

#(source /opt/intel/sw_dev_tools/bin/compilervars.sh intel64; mkdir -p build.icpc        && cd build.icpc        && CXX="icpc"  cmake .. && make -j 10 && ctest -j 10 --output-on-failure) || exit
#(mkdir -p build.icpc-memchk && cd build.icpc-memchk && CXX="icpc"  cmake .. && make -j && ctest -T memcheck -j --output-on-failure) || exit

