$(ODIR)/Communicate.o: $(OHMMSDIR)/src/Message/Communicate.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c \
	$(OHMMSDIR)/src/Message/Communicate.cpp -o $(ODIR)/Communicate.o
$(ODIR)/CommCreate.o: $(OHMMSDIR)/src/Message/CommCreate.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c \
	$(OHMMSDIR)/src/Message/CommCreate.cpp -o $(ODIR)/CommCreate.o

