//////////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the University of Illinois/NCSA Open Source License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2016 Jeongnim Kim and QMCPACK developers.
//
// File developed by: Jeongnim Kim, jeongnim.kim@intel.com, Intel Inc.
//                    Jeremy McMinnis, jmcminis@gmail.com, Navar Inc.
//
// File created by: Jeongnim Kim, jeongnim.kim@intel.com, Intel Inc.
//////////////////////////////////////////////////////////////////////////////////////
    
    



$(ODIR)/Communicate.o: $(OHMMSDIR)/src/Message/Communicate.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c \
	$(OHMMSDIR)/src/Message/Communicate.cpp -o $(ODIR)/Communicate.o
$(ODIR)/CommCreate.o: $(OHMMSDIR)/src/Message/CommCreate.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c \
	$(OHMMSDIR)/src/Message/CommCreate.cpp -o $(ODIR)/CommCreate.o

