# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/grapheneC_1x1_pp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "det_qmc_short_z10.in.xml")
set_tests_properties(deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;deterministic;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/grapheneC_1x1_pp/deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;6;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;0;")
add_test(deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1-ionion "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "det_qmc_short_z10" "-e" "2" "--ii" "14.00211652 0.000002")
set_tests_properties(deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1-ionion PROPERTIES  DEPENDS "deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/grapheneC_1x1_pp/deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;6;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;0;")
add_test(deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "det_qmc_short_z30.in.xml")
set_tests_properties(deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;deterministic;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/grapheneC_1x1_pp/deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;23;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;0;")
add_test(deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1-ionion "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "det_qmc_short_z30" "-e" "2" "--ii" "81.60576396 0.000006")
set_tests_properties(deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1-ionion PROPERTIES  DEPENDS "deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/grapheneC_1x1_pp/deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;23;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/grapheneC_1x1_pp/CMakeLists.txt;0;")
