#!/bin/bash
#COBALT -q default
#COBALT -A PSFMat
#COBALT -n 256
#COBALT -t 30
#COBALT -O vmc

LOCARGS="--block $COBALT_PARTNAME ${COBALT_CORNER:+--corner} $COBALT_CORNER ${COBALT_SHAPE:+--shape} $COBALT_SHAPE"

file_prefix=NiO-fcc-SXX-dmc
exe=/soft/applications/qmcpack/current/build_XL_real/bin/qmcpack

time runjob --np $COBALT_PARTSIZE -p 1 $LOCARGS --verbose=INFO --envs OMP_NUM_THREADS=16 : $exe $file_prefix.xml > $file_prefix.out
