# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/src/QMCTools/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(deterministic-unit_test_tools "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/src/QMCTools/tests/test_tools")
set_tests_properties(deterministic-unit_test_tools PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "quality_unknown;deterministic;unit" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/src/QMCTools/tests" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/unit_test.cmake;8;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;29;add_unit_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(check-affinity_runs "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmc-check-affinity")
set_tests_properties(check-affinity_runs PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "OpenMP" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;34;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(get-supercell_verbose "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmc-get-supercell" "--ptvs" "1" "0" "0" "0" "1" "0" "0" "0" "1" "--target" "8" "--maxentry" "4" "--verbose")
set_tests_properties(get-supercell_verbose PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "radius = 1" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;62;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(get-supercell_terse "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmc-get-supercell" "--ptvs" "1" "0" "0" "0" "1" "0" "0" "0" "1" "--target" "8")
set_tests_properties(get-supercell_terse PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "1   2   0   0   0   2   0   0   0   2   2   0   0   0   2   0   0   0   2" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;84;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(extract-eshdf-kvectors_1x1x1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmc-extract-eshdf-kvectors" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/diamondC_1x1x1_pp/pwscf.pwscf.h5")
set_tests_properties(extract-eshdf-kvectors_1x1x1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "0   0   0" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;108;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(extract-eshdf-kvectors_2x1x1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmc-extract-eshdf-kvectors" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/diamondC_2x1x1_pp/pwscf.pwscf.h5")
set_tests_properties(extract-eshdf-kvectors_2x1x1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "0   0   0
0.5   0   0" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;129;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
add_test(convert4qmc_usage "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/convert4qmc")
set_tests_properties(convert4qmc_usage PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=3" LABELS "deterministic" PASS_REGULAR_EXPRESSION "Usage:" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;152;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/src/QMCTools/tests/CMakeLists.txt;0;")
