##################################################################
##  (c) Copyright 2015-  by Jaron T. Krogel                     ##
##################################################################


#====================================================================#
#  nexus.py                                                          #
#    Gathering place for user-facing Nexus functions.  Management    #
#    of user-provided settings.                                      #
#                                                                    #
#  Content summary:                                                  #
#    Settings                                                        #
#      Class to set 'global' Nexus data.                             #
#                                                                    #
#    settings                                                        #
#      A single Settings instance users interact with as a function. #
#                                                                    #
#    run_project                                                     #
#      User interface to the ProjectManager.                         #
#      Runs all simulations generated by the user.                   #
#                                                                    #
#====================================================================#

import os
import sys
from copy import deepcopy
import importlib
from importlib.metadata import PackageNotFoundError
from pathlib import Path
from collections.abc import Collection

from .nexus_version import nexus_version
from .developer     import obj, NexusError, warn
from .debug         import ci
from .utilities     import path_string

from .nexus_base      import NexusCore, NexusConfig, SimStage, ShowStatusMode, nexus_config, write_splash
from .machines        import Job,                    job,            Machine, Supercomputer, get_machine, get_cpu_cores, Workstation
from .simulation      import Simulation, generate_simulation, input_template, multi_input_template, generate_template_input, generate_multi_template_input, graph_sims, DynamicProcess
from .project_manager import ProjectManager,     DynamicWorkflowManager,     workflow_manager

from .structure       import Structure,          generate_structure,         generate_cell,  read_structure
from .physical_system import PhysicalSystem,     generate_physical_system
from .pseudopotential import Pseudopotential
from .pseudoset       import PseudoSet, ppset, generate_pseudoset
from .basisset        import BasisSets
from .bundle          import bundle

from .pwscf   import Pwscf  , PwscfInput  , PwscfAnalyzer  , generate_pwscf_input  , generate_pwscf
from .gamess  import Gamess , GamessInput , GamessAnalyzer , generate_gamess_input , generate_gamess, FormattedGroup
from .vasp    import Vasp   , VaspInput   , VaspAnalyzer   , generate_vasp_input   , generate_vasp
from .qmcpack import Qmcpack, QmcpackInput, QmcpackAnalyzer, generate_qmcpack_input, generate_qmcpack
from .quantum_package import QuantumPackage,QuantumPackageInput,QuantumPackageAnalyzer,generate_quantum_package_input,generate_quantum_package
from .pyscf_sim import Pyscf, PyscfInput, PyscfAnalyzer, generate_pyscf_input, generate_pyscf
from .rmg import Rmg, RmgInput, RmgAnalyzer, generate_rmg_input, generate_rmg

from .qmcpack_converters import Pw2qmcpack , Pw2qmcpackInput , Pw2qmcpackAnalyzer , generate_pw2qmcpack_input , generate_pw2qmcpack
from .qmcpack_converters import Convert4qmc, Convert4qmcInput, Convert4qmcAnalyzer, generate_convert4qmc_input, generate_convert4qmc
from .qmcpack_converters import Convertpw4qmc, Convertpw4qmcInput, Convertpw4qmcAnalyzer, generate_convertpw4qmc_input, generate_convertpw4qmc
from .qmcpack_converters import PyscfToAfqmc, PyscfToAfqmcInput, PyscfToAfqmcAnalyzer, generate_pyscf_to_afqmc_input, generate_pyscf_to_afqmc

from .pwscf_postprocessors import PP      , PPInput      , PPAnalyzer      , generate_pp_input      , generate_pp
from .pwscf_postprocessors import Dos     , DosInput     , DosAnalyzer     , generate_dos_input     , generate_dos
from .pwscf_postprocessors import Bands   , BandsInput   , BandsAnalyzer   , generate_bands_input   , generate_bands
from .pwscf_postprocessors import Projwfc , ProjwfcInput , ProjwfcAnalyzer , generate_projwfc_input , generate_projwfc
from .pwscf_postprocessors import Cppp    , CpppInput    , CpppAnalyzer    , generate_cppp_input    , generate_cppp
from .pwscf_postprocessors import Pwexport, PwexportInput, PwexportAnalyzer, generate_pwexport_input, generate_pwexport
from .pwscf_postprocessors import Hp      , HpInput      , HpAnalyzer      , generate_hp_input      , generate_hp

from .qmcpack import loop,linear,cslinear,vmc,dmc
from .qmcpack import generate_jastrows,generate_jastrow,generate_jastrow1,generate_jastrow2,generate_jastrow3,generate_opt,generate_opts
from .qmcpack import generate_cusp_correction


#set the machine if known, otherwise user will provide
hostmachine = Machine.get_hostname()
if Machine.exists(hostmachine):
    Job.machine = hostmachine
    ProjectManager.machine = Machine.get(hostmachine)
#end if


# test needed
def run_project(*args,**kwargs):
    if nexus_config.graph_sims:
        graph_sims()
    #end if
    pm = ProjectManager()
    pm.add_simulations(*args,**kwargs)
    pm.run_project()
    return pm
#end def run_project


# test needed
# read input function
#   place here for now as it depends on all other input functions
def read_input(filepath,format=None):
    if not os.path.exists(filepath):
        msg = f'cannot read input file\nfile does not exist: {filepath}'
        raise FileNotFoundError(msg)
    #end if
    if format is None:
        if filepath.endswith('in.xml'):
            format = 'qmcpack'
        else:
            msg = f'cannot identify file format\nplease provide format for file: {filepath}'
            raise RuntimeError(msg)
        #end if
    #end if
    format = format.lower()
    if format=='qmcpack':
        input = QmcpackInput(filepath)
    elif format=='pwscf':
        input = PwscfInput(filepath)
    elif format=='gamess':
        input = GamessInput(filepath)
    else:
        msg = f'cannot read input file\nfile format "{format}" is unsupported'
        raise NotImplementedError(msg)
    #end if
    return input
#end def read_input



def analyze_output(code=None,input=None,outfile=None,*,analyze=True,path=None,**kw):
    """Construct or load an analyzer for output from a supported code.

    Parameters
    ----------
    code : str or Simulation
        Case-insensitive code identifier, or a ``Simulation`` object.  When a
        simulation is supplied, it must be the only argument.  Its saved
        analyzer image is loaded when present; otherwise its analyzer is
        constructed and analyzed.
    input : Simulation, SimulationInput, str, or os.PathLike, optional
        Simulation or code-specific input.  A path may name an input file or,
        where supported, a directory containing one.
    outfile : str or os.PathLike, optional
        Path to the primary text-output file.  PWSCF and RMG accept this
        argument directly; other analyzers map it only where noted below.
    analyze : bool, default=True
        Perform analysis when constructing a new analyzer.  Simulation-image
        loading is unaffected.
    path : str or os.PathLike, optional
        Base directory for relative ``input``, ``outfile``, and other
        code-specific file paths.
    **kw
        Additional keyword arguments for the selected analyzer signature.
        Unknown keyword arguments raise ``ValueError``.

    Notes
    -----
    .. rubric:: Simulation signature

    .. code-block:: python

       analyze_output(sim)

    sim : Simulation
        Simulation produced by a Nexus ``generate_*`` function.  Its saved
        analyzer image is returned when available; otherwise its analyzer is
        constructed with ``analyze=True``.

    .. rubric:: PWSCF signature

    .. code-block:: python

       analyze_output(
           'pwscf', input=None, outfile=None, analyze=True, path=None,
           xmlfile=None, pw2c_outfile=None, read_all=True, strict=True,
           required=None,
           )

    input : PwscfInput, Simulation, str, or os.PathLike, optional
        PWSCF input object, simulation, input-file path, or directory.
    outfile : str or os.PathLike, optional
        PWSCF text-output path.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for relative file paths and file discovery.
    xmlfile : str or os.PathLike, optional
        Explicit modern ``data-file-schema.xml`` path.
    pw2c_outfile : str or os.PathLike, optional
        Optional PW2CASINO text-output path. Relative paths are resolved below
        ``path``.
    read_all : bool, default=True
        Read all available modern XML and text output.  If ``False``, read XML
        first and read text output only when a constructor-required quantity
        remains unavailable.
    strict : bool, default=True
        Require explicitly supplied files, reject ambiguous discovery, and
        require at least one PWSCF XML or text-output source.
    required : str or iterable of str, optional
        Quantities whose unavailable query functions must raise exceptions.

    .. rubric:: RMG signature

    .. code-block:: python

       analyze_output(
           'rmg', input=None, outfile=None, analyze=True, path=None,
           strict=True, required=None,
           )

    input : RmgInput, Simulation, str, or os.PathLike, optional
        RMG input object, simulation, input-file path, or directory.
    outfile : str or os.PathLike, optional
        RMG log-output path.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for relative file paths and output discovery.
    strict : bool, default=True
        Require supplied files, reject ambiguous discovery, and require an
        RMG log-output file.
    required : str or iterable of str, optional
        Quantities whose unavailable query functions must raise exceptions.

    .. rubric:: QMCPACK signature

    .. code-block:: python

       analyze_output(
           'qmcpack', input=None, analyze=True, path=None, source=None,
           destination=None, savefile='',
           methods=None, calculations=None, data_sources=None,
           quantities=None, warmup_calculations=None,
           output=('averages', 'samples'), ndmc_blocks=1000,
           equilibration=None, group_num=None, traces=False,
           dm_settings=None, verbose=False, nindent=0, ghost_atoms=sequence,
           )

    input : str or os.PathLike, optional
        QMCPACK input file or bundled-output path.  Mapped to the analyzer's
        primary source and mutually exclusive with ``source``.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative ``input`` path, or the primary source
        when ``input`` is omitted.
    source : str or os.PathLike, optional
        QMCPACK input file or bundled-output path.  Mutually exclusive with
        ``path``.
    destination : str or os.PathLike, optional
        Directory in which analysis data and optional saved results reside.
    savefile : str, default=''
        Name of an optional saved analyzer image to load or write.
    methods : iterable of str, optional
        QMC method types to analyze.
    calculations : iterable of int, optional
        Calculation-series indices to analyze.
    data_sources : iterable of str, optional
        Output-data source types to include in the analysis.
    quantities : iterable of str, optional
        Observable quantities to analyze.
    warmup_calculations : iterable of int, optional
        Calculation-series indices used only for equilibration data.
    output : iterable of {'averages', 'samples'}, default=('averages', 'samples')
        Analysis result types to produce.
    ndmc_blocks : int, default=1000
        Number of DMC blocks used for derived DMC analyses.
    equilibration : int or dict, optional
        Equilibration period or calculation-specific equilibration settings.
    group_num : int, optional
        Bundle group number to analyze.
    traces : bool, default=False
        Include trace-file analysis.
    dm_settings : dict, optional
        Density-matrix analysis settings.
    verbose : bool, default=False
        Enable verbose analyzer logging.
    nindent : int, default=0
        Initial indentation level for analyzer logging.
    ghost_atoms : sequence, optional
        Atom indices treated as ghost atoms during analysis.

    .. rubric:: VASP signature

    .. code-block:: python

       analyze_output(
           'vasp', input=None, outfile=None, analyze=True, path=None,
           xml=False,
           )

    input : str or os.PathLike, optional
        VASP ``INCAR`` or ``OUTCAR`` path; this is the primary argument.
    outfile : str or os.PathLike, optional
        VASP ``OUTCAR`` path used when ``input`` is omitted.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative input or output path.
    xml : bool, default=False
        Parse ``vasprun.xml`` in addition to text outputs.

    .. rubric:: GAMESS signature

    .. code-block:: python

       analyze_output(
           'gamess', input=None, analyze=True, path=None, prefix=None,
           exit=False,
           )

    input : str or os.PathLike, optional
        GAMESS input file associated with the output to analyze.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative input path, or the input path when
        ``input`` is omitted.
    prefix : str, optional
        Prefix used to locate GAMESS output and punch files.  The input-file
        stem is used when this is not provided.
    exit : bool, default=False
        Enable analysis of the GAMESS exit file.

    Returns
    -------
    SimulationAnalyzer
        Newly constructed and analyzed code-specific analyzer, or an analyzer
        loaded from a simulation image.

    Raises
    ------
    TypeError
        If ``code`` is neither a string nor a ``Simulation`` object.
    ValueError
        If incompatible or unrecognized keyword arguments are supplied.
    NotImplementedError
        If ``code`` does not identify a supported analyzer.
    """

    if isinstance(input,os.PathLike):
        input = path_string(input)
    if isinstance(outfile,os.PathLike):
        outfile = path_string(outfile)
    if isinstance(path,os.PathLike):
        path = path_string(path)
    for name,value in kw.items():
        if isinstance(value,os.PathLike):
            kw[name] = path_string(value)
        #end if
    #end for

    # Retrieve analyzer from a Simulation object
    simulation_types = {
        'qmcpack' : Qmcpack,
        'pwscf'   : Pwscf,
        'rmg'     : Rmg,
        'vasp'    : Vasp,
        'gamess'  : Gamess,
        }
    sim = None
    if isinstance(code,Simulation):
        sim = code
        if (
            input is not None
            or outfile is not None
            or analyze is not True
            or path is not None
            or len(kw)>0
            ):
            msg = (
                'Cannot analyze output.\n'
                'You provided a Simulation object (allowed),\n'
                '\nbut also included additional arguments (not allowed).\n'
                f'Invalid arguments: {sorted(kw)}'
                )
            raise ValueError(msg)
    elif code is None and isinstance(input,Simulation):
        sim = input
        if outfile is not None or analyze is not True or path is not None or len(kw)>0:
            msg = (
                'Cannot analyze output.\n'
                'You provided a Simulation object as "input" (allowed),\n'
                'but also included additional arguments (not allowed).'
                )
            raise ValueError(msg)
    elif isinstance(code,str):
        code = code.lower()
        if isinstance(input,Simulation):
            sim = input
            if outfile is not None or analyze is not True or path is not None or len(kw)>0:
                msg = (
                    'Cannot analyze output.\n'
                    'You provided a Simulation object as "input" (allowed),\n'
                    'but also included additional arguments (not allowed).'
                    )
                raise ValueError(msg)
            if code not in simulation_types or not isinstance(sim,simulation_types[code]):
                msg = (
                    'Cannot analyze output.\n'
                    f'Code "{code}" does not match the provided '
                    f'{sim.__class__.__name__} object.'
                    )
                raise ValueError(msg)
    else:
        msg = (
            'Cannot analyze output.\n'
            'Argument "code" must be provided as a string or a Simulation object.\n'
            'You provided: '+type(code).__name__
            )
        raise TypeError(msg)

    if sim is not None:
        imagepath = os.path.join(sim.imresdir,sim.analyzer_image)
        if os.path.isfile(imagepath):
            return sim.load_analyzer_image()
        return sim.analyzer_type(sim,analyze=True)

    # Construct an analyzer directly from inputs
    if path is not None:
        path = path_string(path)
    if code=='qmcpack':
        qmcpack_kw = dict(analyze=analyze)
        for name in (
            'verbose','nindent','ghost_atoms','source','destination','savefile',
            'methods','calculations','data_sources','quantities',
            'warmup_calculations','output','ndmc_blocks','equilibration',
            'group_num','traces','dm_settings',
            ):
            if name in kw:
                qmcpack_kw[name] = kw.pop(name)
        if outfile is not None:
            raise ValueError('QMCPACK output does not accept "outfile"')
        if input is not None and 'source' in qmcpack_kw:
            msg = (
                'Cannot analyze QMCPACK output.\n'
                'Specify either "input" or "source", not both.'
                )
            raise ValueError(msg)
        source = input
        if source is None:
            source = path
        elif path is not None and isinstance(source,(str,os.PathLike)):
            source = path_string(source)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = QmcpackAnalyzer(source,**qmcpack_kw)
    elif code=='pwscf':
        analyzer = PwscfAnalyzer(
            input,
            outfile,
            analyze           = analyze,
            path              = path,
            xmlfile           = kw.pop('xmlfile',None),
            pw2c_outfile      = kw.pop('pw2c_outfile',None),
            read_all          = kw.pop('read_all',True),
            strict            = kw.pop('strict',True),
            required          = kw.pop('required',None),
            )
    elif code=='rmg':
        analyzer = RmgAnalyzer(
            input,
            outfile,
            analyze  = analyze,
            path     = path,
            strict   = kw.pop('strict',True),
            required = kw.pop('required',None),
            )
    elif code=='vasp':
        if input is not None and outfile is not None:
            raise ValueError('VASP output accepts either "input" or "outfile", not both')
        source = input if input is not None else outfile
        if source is None:
            source = path
        elif path is not None and isinstance(source,(str,os.PathLike)):
            source = path_string(source)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = VaspAnalyzer(
            source,
            xml     = kw.pop('xml',False),
            analyze = analyze,
            )
    elif code=='gamess':
        if outfile is not None:
            raise ValueError('GAMESS output does not accept "outfile"')
        source = input if input is not None else path
        if input is not None and path is not None and isinstance(input,(str,os.PathLike)):
            source = path_string(input)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = GamessAnalyzer(
            source,
            prefix  = kw.pop('prefix',None),
            exit    = kw.pop('exit',False),
            analyze = analyze,
            )
    else:
        msg = (
            f'Cannot analyze output.\nCode "{code}" is unsupported.\n'
            'Valid options are: qmcpack, pwscf, rmg, vasp, gamess'
            )
        raise NotImplementedError(msg)
    if len(kw)>0:
        msg = (
            f'Cannot analyze {code} output.\n'
            'You provided unrecognized arguments.\n'
            f'Unrecognized arguments: {sorted(kw)}'
            )
        raise ValueError(msg)
    return analyzer
#end def analyze_output



class Settings(NexusCore):
    singleton = None

    machine_vars = frozenset({
        'interactive_cores', 'machine_info', 'machine', 'machine_mode', 'user', 'account'
        })

    gamess_vars  = frozenset({'ericfmt', 'mcppath'})

    pwscf_vars   = frozenset({'vdw_table'})

    qm_package_vars = frozenset({'qprc'})

    deprecated_vars = frozenset({
        'mode', 'verbose', 'debug', 'trace', 'emulate'
        })

    nexus_vars = frozenset(NexusConfig.__slots__)
    allowed_vars = (
        nexus_vars
        | machine_vars
        | deprecated_vars
        | gamess_vars
        | pwscf_vars
        | qm_package_vars
        )


    @staticmethod
    def kw_set(vars,source=None):
        kw = obj()
        if source is not None:
            for n in vars:
                if n in source:
                    kw[n]=source[n]
                    del source[n]
                #end if
            #end for
        #end if
        return kw
    #end def null_kw_set


    def __init__(self):
        if Settings.singleton is None:
            Settings.singleton = self
        else:
            msg = 'attempted to create a second Settings object\nplease just use the original'
            raise RuntimeError(msg)
        #end if
    #end def __init__


    # sets up Nexus core class behavior and passes information to broader class structure
    def __call__(self,**kwargs):
        kwargs = obj(**kwargs)
        # Ensure no pathlib.Path objects are stored
        core_path_vars = (
            "runs",
            "results",
            "pseudo_dir",
            "local_directory",
            "remote_directory",
            )
        for var in core_path_vars:
            if var in kwargs:
                kwargs[var] = path_string(kwargs[var])

        # guard against invalid settings
        not_allowed = set(kwargs.keys()) - Settings.allowed_vars
        if len(not_allowed)>0:
            msg = f'unrecognized variables provided\nyou provided: {sorted(not_allowed)}\nallowed variables are: {sorted(Settings.allowed_vars)}'
            raise ValueError(msg)
        #end if

        # restore default core default settings
        nexus_config.restore_defaults()

        # process command line inputs, if any
        if 'command_line' in kwargs:
            nexus_config.command_line = kwargs.command_line
        #end if
        if nexus_config.command_line:
            self.process_command_line_settings(kwargs)
        #end if

        write_splash()

        # print version information
        self.nxs_print("Checking current machine for Nexus dependencies...\n")
        pkg_sort = {
            "numpy":      0,
            "scipy":      1,
            "h5py":       2,
            "matplotlib": 3,
            "spglib":     4,
            "cif2cell":   5,
            "pydot":      6,
            "seekpath":   7,
            }

        try:
            nxs_requirements = importlib.metadata.requires("nexus")
            nxs_deps = {}
            for req in nxs_requirements:
                pkg_name = req.split("=")[0][:-1]
                pkg_ver_min = req.split(">=")[-1]
                if ";" in pkg_ver_min:
                    pkg_ver_min = pkg_ver_min.split(";")[0]
                    status = "optional"
                else:
                    status = "required"

                nxs_deps[pkg_name] = {"min_ver": pkg_ver_min, "status": status}
        except PackageNotFoundError:
            nxs_deps = {
                "numpy":      {"min_ver": "x.x.x", "status": "required"},
                "scipy":      {"min_ver": "x.x.x", "status": "optional"},
                "h5py":       {"min_ver": "x.x.x", "status": "optional"},
                "matplotlib": {"min_ver": "x.x.x", "status": "optional"},
                "spglib":     {"min_ver": "x.x.x", "status": "optional"},
                "cif2cell":   {"min_ver": "x.x.x", "status": "optional"},
                "pydot":      {"min_ver": "x.x.x", "status": "optional"},
                "seekpath":   {"min_ver": "x.x.x", "status": "optional"},
                }

        nxs_deps = dict(sorted(nxs_deps.items(), key=lambda x: pkg_sort.get(x[0], 1000)))

        available_pkgs = {}
        for module in nxs_deps:
            if importlib.util.find_spec(module) is not None:
                available_pkgs[module] = importlib.metadata.version(module)
            else:
                available_pkgs[module] = "Unavailable"

        version_text = ""

        name_align = max([len(i) for i in nxs_deps])
        version_text +=  "  Currently Available Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} = {sys.version.split()[0]}\n"
        for pkg_name, pkg_ver in available_pkgs.items():
            version_text += f"    {pkg_name:<{name_align}} = {pkg_ver:<11} ({nxs_deps[pkg_name]['status']})\n"

        version_text +=  "\n"
        version_text +=  "  Recommended Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} >= 3.10.0\n"
        for pkg_name, pkg_info in nxs_deps.items():
            version_text += f"    {pkg_name:<{name_align}} >= {pkg_info['min_ver']:<10} ({pkg_info['status']})\n"

        version_text += "\n"
        missing_deps = set(nxs_deps) - {i for i, a in available_pkgs.items() if a != "Unavailable"}
        if len(missing_deps) > 0:
            version_text += "  Required dependencies are met,\n"
            version_text += "  however some optional dependencies are missing.\n"
            version_text += "  Some features of Nexus may be unavailable.\n\n"

            version_text += "  Missing dependencies:\n"
            for missing in missing_deps:
                version_text += f"    - {missing} ({nxs_deps[missing]['status']})\n"
        else:
            version_text += "  All dependencies are present.\n"

        version_text += "\n"

        self.nxs_print(version_text)

        self.nxs_print('Applying user settings')

        # extract settings based on keyword groups
        kw        = Settings.kw_set(Settings.nexus_vars | Settings.deprecated_vars, kwargs)
        mach_kw   = Settings.kw_set(Settings.machine_vars   ,kwargs)
        gamess_kw = Settings.kw_set(Settings.gamess_vars    ,kwargs)
        pwscf_kw  = Settings.kw_set(Settings.pwscf_vars     ,kwargs)
        qm_pkg_kw = Settings.kw_set(Settings.qm_package_vars,kwargs)
        if len(kwargs)>0:
            msg = (
                'Some settings keywords have not been accounted for\n'
                f'Leftover keywords: {sorted(kwargs.keys())}\n'
                'This is a developer error'
            )
            raise NexusError(msg)
        #end if


        # copy input settings
        self.update(**deepcopy(mach_kw))
        self.update(**deepcopy(gamess_kw))
        self.update(**deepcopy(pwscf_kw))

        # process machine settings
        self.process_machine_settings(mach_kw)

        # process nexus config settings
        self.process_config_settings(kw)
        self.update(**{s: getattr(nexus_config, s) for s in Settings.nexus_vars})

        # process gamess settings
        Gamess.restore_default_settings()
        Gamess.settings(**gamess_kw)

        # process pwscf settings
        Pwscf.restore_default_settings()
        Pwscf.settings(**pwscf_kw)

        # process quantum package settings
        QuantumPackage.restore_default_settings()
        QuantumPackage.settings(**qm_pkg_kw)
    #end def __call__


    def process_command_line_settings(self, script_settings: obj):
        import argparse
        from argparse import ArgumentParser

        parser = ArgumentParser()
        parser.add_argument(
            "--version",
            action="version",
            version="Nexus {}.{}.{}".format(*nexus_version)
            )
        parser.add_argument(
            "--status-only",
            "--status_only",
            action="store_true",
            default=argparse.SUPPRESS,
            help=(
                "Report status of all simulations and then exit. "
                f"(default: {nexus_config.status_only})"
                )
            )
        parser.add_argument(
            "--status",
            default=argparse.SUPPRESS,
            choices=("all", "active", "failed", "ready", "standard"),
            help=(
                "Controls displayed simulation status information. "
                f"(default: {nexus_config.status})"
                )
            )
        parser.add_argument(
            "--generate-only",
            "--generate_only",
            action="store_true",
            default=argparse.SUPPRESS,
            help=(
                "Write inputs to all simulations and then exit. "
                "Note that no dependencies are processed, "
                "e.g. if one simulation depends on another for an "
                "orbital file location or for a relaxed structure, "
                "this information will not be present in the generated "
                "input file for that simulation since no simulations are "
                "actually run with this option. "
                f"(default: {nexus_config.generate_only})"
                )
            )
        parser.add_argument(
            "--graph-sims",
            "--graph_sims",
            action="store_true",
            default=argparse.SUPPRESS,
            help=(
                "Display a graph of simulation workflows, then exit. "
                f"(default: {nexus_config.graph_sims})"
                )
            )
        parser.add_argument(
            "--progress-tty",
            "--progress_tty",
            action="store_true",
            default=argparse.SUPPRESS,
            help=(
                "Print abbreviated polling messages. "
                f"(default: {nexus_config.progress_tty})"
                )
            )
        parser.add_argument(
            "--sleep",
            type=float,
            default=argparse.SUPPRESS,
            help=(
                "Number of seconds between polls. "
                "At each poll, simulations are actually run provided all "
                "simulations they depend on have successfully completed "
                f"(default: {nexus_config.sleep})."
                )
            )
        parser.add_argument(
            "--timeout",
            type=float,
            default=argparse.SUPPRESS,
            help=(
                "Number of seconds to wait for output and error files after "
                "a job exits the queue before marking the simulation as failed "
                f"(default: {nexus_config.timeout})."
                )
            )
        parser.add_argument(
            "--machine",
            choices=(
                "ws",
                "ws{1-128}",
                "workstation",
                *[m for m in Machine.machines if not m.startswith("ws")],
                ),
            default=argparse.SUPPRESS,
            help=(
                "Name of the machine the simulations will be run on. "
                "Workstations may be specified by 'ws', which will "
                "automatically detect the number of cores "
                "(works for any machine where only mpirun is used). "
                "For a complete listing of currently available machines "
                "(including those at HPC centers) please see the manual."
                )
            )
        parser.add_argument(
            "--account",
            default=argparse.SUPPRESS,
            help="Account name required to submit jobs at some HPC centers."
            )
        parser.add_argument(
            "--runs",
            default=argparse.SUPPRESS,
            help=(
                "Directory to perform all runs in. "
                "Simulation paths are appended to this directory "
                f"(default: {nexus_config.runs})."
                )
            )
        parser.add_argument(
            "--results",
            default=argparse.SUPPRESS,
            help=(
                "Directory to copy out lightweight results data. "
                "If set to '', results will not be stored outside of the runs "
                f"directory (default: {nexus_config.results})."
                )
            )
        parser.add_argument(
            "--local-directory",
            "--local_directory",
            default=argparse.SUPPRESS,
            help=(
                "Base path where runs and results directories will be created "
                f"(default={nexus_config.local_directory})."
                )
            )
        parser.add_argument(
            "--pseudo-dir",
            "--pseudo_dir",
            default=argparse.SUPPRESS,
            help=(
                "Path to directory containing pseudopotential files "
                "(required if running with pseudopotentials)."
                )
            )
        parser.add_argument(
            "--basis-dir",
            "--basis_dir",
            default=argparse.SUPPRESS,
            help=(
                "Path to directory containing basis set files "
                "(useful if running gaussian based QMC workflows)."
                )
            )
        parser.add_argument(
            "--ericfmt",
            default=argparse.SUPPRESS,
            help=(
                "Path to the ericfmt file used with GAMESS "
                "(required if running GAMESS)."
                )
            )
        parser.add_argument(
            "--mcppath",
            default=argparse.SUPPRESS,
            help=(
                "Path to the mcpdata file used with GAMESS "
                "(optional for most workflows)"
                )
            )
        parser.add_argument(
            "--vdw-table",
            "--vdw_table",
            default=argparse.SUPPRESS,
            help=(
                "Path to the vdw_table file used with Quantum ESPRESSO "
                "(required only if running QE with van der Waals functionals)."
                )
            )
        parser.add_argument(
            "--qprc",
            default=argparse.SUPPRESS,
            help="Path to the quantum_package.rc file used with Quantum Package."
            )

        # parse the command line inputs
        args = vars(parser.parse_args())

        # override script settings with command line settings
        for name,value in args.items():
            script_settings[name] = value
    #end def process_command_line_settings


    def process_machine_settings(self,mset):
        Job.restore_default_settings()
        ProjectManager.restore_default_settings()
        mid_set = set()
        if 'machine_info' in mset:
            machine_info = mset.machine_info
            if isinstance(machine_info, dict | obj):
                for machine_name,minfo in machine_info.items():
                    mname = machine_name.lower()
                    if Machine.exists(mname):
                        machine = Machine.get(mname)
                        machine.restore_default_settings()
                        machine.incorporate_user_info(minfo)
                        mid_set.add(id(machine))
                    else:
                        msg = (
                            f'machine {machine_name} is unknown\n'
                            '  cannot set machine_info'
                            )
                        raise ValueError(msg)
                    #end if
                #end for
            else:
                msg = (
                    'machine_info must be a dict or obj\n'
                    '  you provided type '+type(machine_info).__name__
                    )
                raise TypeError(msg)
            #end if
        #end if
        if 'machine' in mset:
            machine_name = mset.machine
            if machine_name in {"ws", "workstation"}:
                self.nxs_print("Automatically detecting physical CPU cores for workstation...", n=1)
                n_cores = get_cpu_cores()
                self.nxs_print(f"Using {n_cores} core workstation", n=1)
                machine_name = f"ws{n_cores}"

                if not Machine.exists(machine_name):
                    # Register a workstation with the determined number of cores
                    # if there is not already one that exists.
                    Workstation(machine_name, n_cores, 'mpirun')

            if not Machine.exists(machine_name):
                msg = f'machine {machine_name} is unknown'
                raise ValueError(msg)
            #end if
            Job.machine = machine_name
            machine = Machine.get(machine_name)
            ProjectManager.machine = machine
            if machine is not None and id(machine) not in mid_set:
                machine.restore_default_settings()
            #end if
            if 'account' in mset:
                account = mset.account
                if not isinstance(account,str):
                    msg = (
                        f'account for {machine_name} must be a string\n'
                        f'you provided: {account}'
                        )
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.account = account
            #end if
            if 'user' in mset:
                user = mset.user
                if not isinstance(user,str):
                    msg = (
                        f'user for {machine_name} must be a string\n'
                        f'you provided: {user}'
                        )
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.user = user
            #end if
            if 'machine_mode' in mset:
                machine_mode = mset.machine_mode
                if machine_mode in Machine.modes:
                    machine_mode = Machine.modes[machine_mode]
                #end if
                if machine_mode==Machine.modes.interactive:
                    if ProjectManager.machine is None:
                        msg = 'no machine specified for interactive mode'
                        raise ValueError(msg)
                    #end if
                    if not isinstance(ProjectManager.machine,Supercomputer):
                        msg = 'interactive mode is not supported for machine type '+ProjectManager.machine.__class__.__name__
                        raise NotImplementedError(msg)
                    #end if
                    if 'interactive_cores' not in mset:
                        msg = 'interactive mode requested, but interactive_cores not set'
                        raise ValueError(msg)
                    #end if
                    ProjectManager.machine = ProjectManager.machine.interactive_representation(mset.interactive_cores)
                    Job.machine = ProjectManager.machine.name
                #end if
            #end if
        #end if
    #end def process_machine_settings


    def process_config_settings(self, kw: dict):
        # Deprecated variables
        deprecated = (
            ("mode", "Please use `stages` instead!"),
            ("verbose", "Please use `quiet=True` to turn off output instead of `verbose=False`!"),
            ("debug", "This variable was redundant, please remove from your script!"),
            ("trace", "This variable was unused in Nexus, please remove from your script!"),
            ("emulate", "This variable was unused in Nexus, please remove from your script!"),
        )
        for var, extra in deprecated:
            if var in kw:
                del kw[var]
                warn(
                    f"The setting '{var}' has been deprecated!\n"
                    f"{extra}"
                    )

        for arg in ("sleep", "timeout"):
            arg_val = kw.get(arg)
            if arg_val is None:
                continue

            if not isinstance(arg_val, float | int):
                msg = f"Setting '{arg}' must be a number, but is {type(arg_val).__name__}!"
                raise TypeError(msg)
            elif arg_val <= 0:
                msg = f"Setting '{arg}' must be greater than zero!"
                raise ValueError(msg)

        match kw.pop("status", None):
            case None | False:
                pass
            case True:
                nexus_config.status = ShowStatusMode.all
            case val:
                val_str = str(val).lower()
                if val_str == "standard":
                    nexus_config.status = ShowStatusMode.all
                elif val_str in ShowStatusMode.__members__:
                    nexus_config.status = ShowStatusMode[val_str]
                else:
                    msg = (
                        f"Invalid status mode specified: {val}\n"
                        f"Valid status modes are: {[i.lower() for i in ShowStatusMode.__members__]}"
                    )
                    raise ValueError(msg)

        if status_only := kw.pop("status_only", None):
            nexus_config.status_only = status_only
            if nexus_config.status is ShowStatusMode.none:
                nexus_config.status = ShowStatusMode.all

        stages = kw.pop("stages", None)
        generate_only = kw.pop("generate_only", None)
        if stages is not None and generate_only is not None:
            msg = "Can not set both `stages` and `generate_only`!"
            raise ValueError(msg)
        elif isinstance(stages, SimStage):
            nexus_config.stages = stages
        elif isinstance(stages, str):
            if stages.lower() not in SimStage.__members__:
                msg = (
                    f"Invalid stages specified: {stages}\n"
                    f"Valid stages are: {[*SimStage.__members__]}"
                )
                raise ValueError(msg)
            nexus_config.stages = SimStage[stages.lower()]
        elif isinstance(stages, Collection):
            nexus_config.stages = SimStage.from_list(stages)
        elif stages is not None:
            msg = f"stages should be a SimStage, str, or list of str, but is {type(stages)}!"
            raise TypeError(msg)
        elif generate_only:
            nexus_config.stages = SimStage.setup # Preferred new route
            nexus_config.generate_only = True # Legacy, will replace

        if (loc_dir := kw.pop("local_directory", None)) is not None:
            nexus_config.local_directory = path_string(loc_dir)
            nexus_config.file_locations.append(path_string(loc_dir))

        if (file_locs := kw.pop("file_locations", None)) is not None:
            if isinstance(file_locs, str | Path):
                nexus_config.file_locations.append(path_string(file_locs))
            else:
                nexus_config.file_locations.extend(
                    path_string(i) for i in file_locs
                )

        if (pseudo_dir := kw.pop("pseudo_dir", None)) is not None:
            pseudo_dir = Path(pseudo_dir).resolve(strict=True)
            if not pseudo_dir.is_dir():
                msg = f"pseudo_dir '{pseudo_dir}' is not a directory!"
                raise NotADirectoryError(msg)

            nexus_config.pseudo_dir = path_string(pseudo_dir)

        PseudoSet.pseudo_files.clear()
        PseudoSet.labeled_pseudosets.clear()
        if nexus_config.pseudo_dir is not None:
            for file in Path(nexus_config.pseudo_dir).iterdir():
                if file.is_file():
                    PseudoSet.pseudo_files[file.name] = str(file)

        # backwards compatibility with prior results_dir default
        old_results_default = 'results'
        old_results_dir = os.path.join(nexus_config.local_directory,old_results_default)
        if 'results' not in kw and os.path.exists(old_results_dir):
            nexus_config.results = old_results_default

        if basis_dir := kw.pop("basis_dir", None):
            basis_dir = Path(basis_dir).resolve(strict=True)
            if not basis_dir.is_dir():
                msg = f"basis_dir '{basis_dir}' is not a directory!"
                raise NotADirectoryError(msg)

            nexus_config.basis_dir = path_string(basis_dir)
            nexus_config.file_locations.append(path_string(basis_dir))
            bs_files = []
            for file in basis_dir.iterdir():
                if file.is_file():
                    bs_files.append(path_string(file))

            nexus_config.basissets = BasisSets(bs_files)
        else:
            nexus_config.basissets = BasisSets()

        # Set remaining settings
        for cfg_var in NexusConfig.__slots__:
            if (cfg_val := kw.pop(cfg_var, None)) is not None:
                setattr(nexus_config, cfg_var, cfg_val)
    #end def process_config_settings
#end class Settings


# create settings functor for UI
settings = Settings()
