##################################################################
##  (c) Copyright 2015-  by Jaron T. Krogel                     ##
##################################################################


#====================================================================#
#  nexus.py                                                          #
#    Gathering place for user-facing Nexus functions.  Management    #
#    of user-provided settings.                                      #
#                                                                    #
#  Content summary:                                                  #
#    Settings                                                        #
#      Class to set 'global' Nexus data.                             #
#                                                                    #
#    settings                                                        #
#      A single Settings instance users interact with as a function. #
#                                                                    #
#    run_project                                                     #
#      User interface to the ProjectManager.                         #
#      Runs all simulations generated by the user.                   #
#                                                                    #
#====================================================================#

import os
import sys
from copy import deepcopy
import importlib
from importlib.metadata import PackageNotFoundError
from pathlib import Path

from .nexus_version import nexus_version
from .developer     import obj, nxs_print, NexusError
from .debug         import ci
from .utilities     import path_string

from .nexus_base      import NexusCore,              nexus_core,     nexus_noncore,          nexus_core_noncore,         restore_nexus_core_defaults,    nexus_core_defaults, write_splash
from .machines        import Job,                    job,            Machine, Supercomputer, get_machine, get_cpu_cores, Workstation
from .simulation      import Simulation, generate_simulation, input_template, multi_input_template, generate_template_input, generate_multi_template_input, graph_sims, DynamicProcess
from .project_manager import ProjectManager,     DynamicWorkflowManager,     workflow_manager

from .structure       import Structure,          generate_structure,         generate_cell,  read_structure
from .physical_system import PhysicalSystem,     generate_physical_system
from .pseudopotential import Pseudopotential
from .pseudoset       import PseudoSet, ppset, generate_pseudoset
from .basisset        import BasisSets
from .bundle          import bundle

from .pwscf   import Pwscf  , PwscfInput  , PwscfAnalyzer  , generate_pwscf_input  , generate_pwscf
from .gamess  import Gamess , GamessInput , GamessAnalyzer , generate_gamess_input , generate_gamess, FormattedGroup
from .vasp    import Vasp   , VaspInput   , VaspAnalyzer   , generate_vasp_input   , generate_vasp
from .qmcpack import Qmcpack, QmcpackInput, QmcpackAnalyzer, generate_qmcpack_input, generate_qmcpack
from .quantum_package import QuantumPackage,QuantumPackageInput,QuantumPackageAnalyzer,generate_quantum_package_input,generate_quantum_package
from .pyscf_sim import Pyscf, PyscfInput, PyscfAnalyzer, generate_pyscf_input, generate_pyscf
from .rmg import Rmg, RmgInput, RmgAnalyzer, generate_rmg_input, generate_rmg

from .qmcpack_converters import Pw2qmcpack , Pw2qmcpackInput , Pw2qmcpackAnalyzer , generate_pw2qmcpack_input , generate_pw2qmcpack
from .qmcpack_converters import Convert4qmc, Convert4qmcInput, Convert4qmcAnalyzer, generate_convert4qmc_input, generate_convert4qmc
from .qmcpack_converters import Convertpw4qmc, Convertpw4qmcInput, Convertpw4qmcAnalyzer, generate_convertpw4qmc_input, generate_convertpw4qmc
from .qmcpack_converters import PyscfToAfqmc, PyscfToAfqmcInput, PyscfToAfqmcAnalyzer, generate_pyscf_to_afqmc_input, generate_pyscf_to_afqmc

from .pwscf_postprocessors import PP      , PPInput      , PPAnalyzer      , generate_pp_input      , generate_pp
from .pwscf_postprocessors import Dos     , DosInput     , DosAnalyzer     , generate_dos_input     , generate_dos
from .pwscf_postprocessors import Bands   , BandsInput   , BandsAnalyzer   , generate_bands_input   , generate_bands
from .pwscf_postprocessors import Projwfc , ProjwfcInput , ProjwfcAnalyzer , generate_projwfc_input , generate_projwfc
from .pwscf_postprocessors import Cppp    , CpppInput    , CpppAnalyzer    , generate_cppp_input    , generate_cppp
from .pwscf_postprocessors import Pwexport, PwexportInput, PwexportAnalyzer, generate_pwexport_input, generate_pwexport
from .pwscf_postprocessors import Hp      , HpInput      , HpAnalyzer      , generate_hp_input      , generate_hp

from .qmcpack import loop,linear,cslinear,vmc,dmc
from .qmcpack import generate_jastrows,generate_jastrow,generate_jastrow1,generate_jastrow2,generate_jastrow3,generate_opt,generate_opts
from .qmcpack import generate_cusp_correction


#set the machine if known, otherwise user will provide
hostmachine = Machine.get_hostname()
if Machine.exists(hostmachine):
    Job.machine = hostmachine
    ProjectManager.machine = Machine.get(hostmachine)
#end if


# test needed
def run_project(*args,**kwargs):
    if nexus_core.graph_sims:
        graph_sims()
    #end if
    pm = ProjectManager()
    pm.add_simulations(*args,**kwargs)
    pm.run_project()
    return pm
#end def run_project


# test needed
# read input function
#   place here for now as it depends on all other input functions
def read_input(filepath,format=None):
    if not os.path.exists(filepath):
        msg = f'cannot read input file\nfile does not exist: {filepath}'
        raise FileNotFoundError(msg)
    #end if
    if format is None:
        if filepath.endswith('in.xml'):
            format = 'qmcpack'
        else:
            msg = f'cannot identify file format\nplease provide format for file: {filepath}'
            raise RuntimeError(msg)
        #end if
    #end if
    format = format.lower()
    if format=='qmcpack':
        input = QmcpackInput(filepath)
    elif format=='pwscf':
        input = PwscfInput(filepath)
    elif format=='gamess':
        input = GamessInput(filepath)
    else:
        msg = f'cannot read input file\nfile format "{format}" is unsupported'
        raise NotImplementedError(msg)
    #end if
    return input
#end def read_input



def analyze_output(code=None,input=None,outfile=None,*,analyze=True,path=None,**kw):
    """Construct or load an analyzer for output from a supported code.

    Parameters
    ----------
    code : str or Simulation
        Case-insensitive code identifier, or a ``Simulation`` object.  When a
        simulation is supplied, it must be the only argument.  Its saved
        analyzer image is loaded when present; otherwise its analyzer is
        constructed and analyzed.
    input : Simulation, SimulationInput, str, or os.PathLike, optional
        Simulation or code-specific input.  A path may name an input file or,
        where supported, a directory containing one.
    outfile : str or os.PathLike, optional
        Path to the primary text-output file.  PWSCF and RMG accept this
        argument directly; other analyzers map it only where noted below.
    analyze : bool, default=True
        Perform analysis when constructing a new analyzer.  Simulation-image
        loading is unaffected.
    path : str or os.PathLike, optional
        Base directory for relative ``input``, ``outfile``, and other
        code-specific file paths.
    **kw
        Additional keyword arguments for the selected analyzer signature.
        Unknown keyword arguments raise ``ValueError``.

    Notes
    -----
    .. rubric:: Simulation signature

    .. code-block:: python

       analyze_output(sim)

    sim : Simulation
        Simulation produced by a Nexus ``generate_*`` function.  Its saved
        analyzer image is returned when available; otherwise its analyzer is
        constructed with ``analyze=True``.

    .. rubric:: PWSCF signature

    .. code-block:: python

       analyze_output(
           'pwscf', input=None, outfile=None, analyze=True, path=None,
           xmlfile=None, pw2c_outfile_name=None, read_all=True, strict=True,
           required=None,
           )

    input : PwscfInput, Simulation, str, or os.PathLike, optional
        PWSCF input object, simulation, input-file path, or directory.
    outfile : str or os.PathLike, optional
        PWSCF text-output path.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for relative file paths and file discovery.
    xmlfile : str or os.PathLike, optional
        Explicit modern ``data-file-schema.xml`` path.
    pw2c_outfile_name : str, optional
        Optional PW2CASINO output-file name within ``path``.
    read_all : bool, default=True
        Read all available modern XML and text output.  If ``False``, read XML
        first and read text output only when a constructor-required quantity
        remains unavailable.
    strict : bool, default=True
        Require explicitly supplied files, reject ambiguous discovery, and
        require at least one PWSCF XML or text-output source.
    required : str or iterable of str, optional
        Quantities whose unavailable query functions must raise exceptions.

    .. rubric:: RMG signature

    .. code-block:: python

       analyze_output(
           'rmg', input=None, outfile=None, analyze=True, path=None,
           strict=True, required=None,
           )

    input : RmgInput, Simulation, str, or os.PathLike, optional
        RMG input object, simulation, input-file path, or directory.
    outfile : str or os.PathLike, optional
        RMG log-output path.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for relative file paths and output discovery.
    strict : bool, default=True
        Require supplied files, reject ambiguous discovery, and require an
        RMG log-output file.
    required : str or iterable of str, optional
        Quantities whose unavailable query functions must raise exceptions.

    .. rubric:: QMCPACK signature

    .. code-block:: python

       analyze_output(
           'qmcpack', input=None, analyze=True, path=None, source=None,
           destination=None, savefile='',
           methods=None, calculations=None, data_sources=None,
           quantities=None, warmup_calculations=None,
           output=('averages', 'samples'), ndmc_blocks=1000,
           equilibration=None, group_num=None, traces=False,
           dm_settings=None, verbose=False, nindent=0, ghost_atoms=sequence,
           )

    input : str or os.PathLike, optional
        QMCPACK input file or bundled-output path.  Mapped to the analyzer's
        primary source and mutually exclusive with ``source``.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative ``input`` path, or the primary source
        when ``input`` is omitted.
    source : str or os.PathLike, optional
        QMCPACK input file or bundled-output path.  Mutually exclusive with
        ``path``.
    destination : str or os.PathLike, optional
        Directory in which analysis data and optional saved results reside.
    savefile : str, default=''
        Name of an optional saved analyzer image to load or write.
    methods : iterable of str, optional
        QMC method types to analyze.
    calculations : iterable of int, optional
        Calculation-series indices to analyze.
    data_sources : iterable of str, optional
        Output-data source types to include in the analysis.
    quantities : iterable of str, optional
        Observable quantities to analyze.
    warmup_calculations : iterable of int, optional
        Calculation-series indices used only for equilibration data.
    output : iterable of {'averages', 'samples'}, default=('averages', 'samples')
        Analysis result types to produce.
    ndmc_blocks : int, default=1000
        Number of DMC blocks used for derived DMC analyses.
    equilibration : int or dict, optional
        Equilibration period or calculation-specific equilibration settings.
    group_num : int, optional
        Bundle group number to analyze.
    traces : bool, default=False
        Include trace-file analysis.
    dm_settings : dict, optional
        Density-matrix analysis settings.
    verbose : bool, default=False
        Enable verbose analyzer logging.
    nindent : int, default=0
        Initial indentation level for analyzer logging.
    ghost_atoms : sequence, optional
        Atom indices treated as ghost atoms during analysis.

    .. rubric:: VASP signature

    .. code-block:: python

       analyze_output(
           'vasp', input=None, outfile=None, analyze=True, path=None,
           xml=False,
           )

    input : str or os.PathLike, optional
        VASP ``INCAR`` or ``OUTCAR`` path; this is the primary argument.
    outfile : str or os.PathLike, optional
        VASP ``OUTCAR`` path used when ``input`` is omitted.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative input or output path.
    xml : bool, default=False
        Parse ``vasprun.xml`` in addition to text outputs.

    .. rubric:: GAMESS signature

    .. code-block:: python

       analyze_output(
           'gamess', input=None, analyze=True, path=None, prefix=None,
           exit=False,
           )

    input : str or os.PathLike, optional
        GAMESS input file associated with the output to analyze.
    analyze : bool, default=True
        Perform analysis during construction.
    path : str or os.PathLike, optional
        Base directory for a relative input path, or the input path when
        ``input`` is omitted.
    prefix : str, optional
        Prefix used to locate GAMESS output and punch files.  The input-file
        stem is used when this is not provided.
    exit : bool, default=False
        Enable analysis of the GAMESS exit file.

    Returns
    -------
    SimulationAnalyzer
        Newly constructed and analyzed code-specific analyzer, or an analyzer
        loaded from a simulation image.

    Raises
    ------
    TypeError
        If ``code`` is neither a string nor a ``Simulation`` object.
    ValueError
        If incompatible or unrecognized keyword arguments are supplied.
    NotImplementedError
        If ``code`` does not identify a supported analyzer.
    """

    # Retrieve analyzer from a Simulation object
    simulation_types = {
        'qmcpack' : Qmcpack,
        'pwscf'   : Pwscf,
        'rmg'     : Rmg,
        'vasp'    : Vasp,
        'gamess'  : Gamess,
        }
    sim = None
    if isinstance(code,Simulation):
        sim = code
        if (
            input is not None
            or outfile is not None
            or analyze is not True
            or path is not None
            or len(kw)>0
            ):
            msg = (
                'Cannot analyze output.\n'
                'You provided a Simulation object (allowed),\n'
                '\nbut also included additional arguments (not allowed).\n'
                f'Invalid arguments: {sorted(kw)}'
                )
            raise ValueError(msg)
    elif code is None and isinstance(input,Simulation):
        sim = input
        if outfile is not None or analyze is not True or path is not None or len(kw)>0:
            msg = (
                'Cannot analyze output.\n'
                'You provided a Simulation object as "input" (allowed),\n'
                'but also included additional arguments (not allowed).'
                )
            raise ValueError(msg)
    elif isinstance(code,str):
        code = code.lower()
        if isinstance(input,Simulation):
            sim = input
            if outfile is not None or analyze is not True or path is not None or len(kw)>0:
                msg = (
                    'Cannot analyze output.\n'
                    'You provided a Simulation object as "input" (allowed),\n'
                    'but also included additional arguments (not allowed).'
                    )
                raise ValueError(msg)
            if code not in simulation_types or not isinstance(sim,simulation_types[code]):
                msg = (
                    'Cannot analyze output.\n'
                    f'Code "{code}" does not match the provided '
                    f'{sim.__class__.__name__} object.'
                    )
                raise ValueError(msg)
    else:
        msg = (
            'Cannot analyze output.\n'
            'Argument "code" must be provided as a string or a Simulation object.\n'
            'You provided: '+type(code).__name__
            )
        raise TypeError(msg)

    if sim is not None:
        imagepath = os.path.join(sim.imresdir,sim.analyzer_image)
        if os.path.isfile(imagepath):
            return sim.load_analyzer_image()
        return sim.analyzer_type(sim,analyze=True)

    # Construct an analyzer directly from inputs
    if path is not None:
        path = path_string(path)
    if code=='qmcpack':
        qmcpack_kw = dict(analyze=analyze)
        for name in (
            'verbose','nindent','ghost_atoms','source','destination','savefile',
            'methods','calculations','data_sources','quantities',
            'warmup_calculations','output','ndmc_blocks','equilibration',
            'group_num','traces','dm_settings',
            ):
            if name in kw:
                qmcpack_kw[name] = kw.pop(name)
        if outfile is not None:
            raise ValueError('QMCPACK output does not accept "outfile"')
        if input is not None and 'source' in qmcpack_kw:
            msg = (
                'Cannot analyze QMCPACK output.\n'
                'Specify either "input" or "source", not both.'
                )
            raise ValueError(msg)
        source = input
        if source is None:
            source = path
        elif path is not None and isinstance(source,(str,os.PathLike)):
            source = path_string(source)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = QmcpackAnalyzer(source,**qmcpack_kw)
    elif code=='pwscf':
        analyzer = PwscfAnalyzer(
            input,
            outfile,
            analyze           = analyze,
            path              = path,
            xmlfile           = kw.pop('xmlfile',None),
            pw2c_outfile_name = kw.pop('pw2c_outfile_name',None),
            read_all          = kw.pop('read_all',True),
            strict            = kw.pop('strict',True),
            required          = kw.pop('required',None),
            )
    elif code=='rmg':
        analyzer = RmgAnalyzer(
            input,
            outfile,
            analyze  = analyze,
            path     = path,
            strict   = kw.pop('strict',True),
            required = kw.pop('required',None),
            )
    elif code=='vasp':
        if input is not None and outfile is not None:
            raise ValueError('VASP output accepts either "input" or "outfile", not both')
        source = input if input is not None else outfile
        if source is None:
            source = path
        elif path is not None and isinstance(source,(str,os.PathLike)):
            source = path_string(source)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = VaspAnalyzer(
            source,
            xml     = kw.pop('xml',False),
            analyze = analyze,
            )
    elif code=='gamess':
        if outfile is not None:
            raise ValueError('GAMESS output does not accept "outfile"')
        source = input if input is not None else path
        if input is not None and path is not None and isinstance(input,(str,os.PathLike)):
            source = path_string(input)
            if not os.path.isabs(source):
                source = os.path.join(path,source)
        analyzer = GamessAnalyzer(
            source,
            prefix  = kw.pop('prefix',None),
            exit    = kw.pop('exit',False),
            analyze = analyze,
            )
    else:
        msg = (
            f'Cannot analyze output.\nCode "{code}" is unsupported.\n'
            'Valid options are: qmcpack, pwscf, rmg, vasp, gamess'
            )
        raise NotImplementedError(msg)
    if len(kw)>0:
        msg = (
            f'Cannot analyze {code} output.\n'
            'You provided unrecognized arguments.\n'
            f'Unrecognized arguments: {sorted(kw)}'
            )
        raise ValueError(msg)
    return analyzer
#end def analyze_output



class Settings(NexusCore):
    singleton = None

    machine_vars = frozenset({
        'interactive_cores', 'machine_info', 'machine', 'machine_mode', 'user', 'account'
        })

    core_assign_vars = frozenset({
        'results', 'load_images', 'remote_directory', 'verbose', 'progress_tty',
        'command_line', 'sleep', 'timeout', 'monitor', 'debug', 'skip_submit', 'dynamic', 'runs',
        'stages', 'pseudo_dir', 'graph_sims', 'generate_only', 'trace',
        'local_directory', 'status_only'
        })

    core_process_vars = frozenset({'file_locations', 'status', 'mode'})

    noncore_assign_vars = frozenset({'basis_dir'})

    noncore_process_vars = frozenset()

    gamess_vars  = frozenset({'ericfmt', 'mcppath'})

    pwscf_vars   = frozenset({'vdw_table'})

    qm_package_vars = frozenset({'qprc'})

    nexus_core_vars    = core_assign_vars    | core_process_vars
    nexus_noncore_vars = noncore_assign_vars | noncore_process_vars
    nexus_vars         = nexus_core_vars     | nexus_noncore_vars
    allowed_vars       = nexus_vars | machine_vars \
                    | gamess_vars | pwscf_vars | qm_package_vars


    @staticmethod
    def kw_set(vars,source=None):
        kw = obj()
        if source is not None:
            for n in vars:
                if n in source:
                    kw[n]=source[n]
                    del source[n]
                #end if
            #end for
        #end if
        return kw
    #end def null_kw_set


    def __init__(self):
        if Settings.singleton is None:
            Settings.singleton = self
        else:
            msg = 'attempted to create a second Settings object\nplease just use the original'
            raise RuntimeError(msg)
        #end if
    #end def __init__


    # sets up Nexus core class behavior and passes information to broader class structure
    def __call__(self,**kwargs):
        kwargs = obj(**kwargs)
        # Ensure no pathlib.Path objects are stored
        core_path_vars = (
            "runs",
            "results",
            "pseudo_dir",
            "local_directory",
            "remote_directory",
            )
        for var in core_path_vars:
            if var in kwargs:
                kwargs[var] = path_string(kwargs[var])

        # guard against invalid settings
        not_allowed = set(kwargs.keys()) - Settings.allowed_vars
        if len(not_allowed)>0:
            msg = f'unrecognized variables provided\nyou provided: {sorted(not_allowed)}\nallowed variables are: {sorted(Settings.allowed_vars)}'
            raise ValueError(msg)
        #end if

        # restore default core default settings
        restore_nexus_core_defaults()

        # process command line inputs, if any
        if 'command_line' in kwargs:
            nexus_core.command_line = kwargs.command_line
        #end if
        if nexus_core.command_line:
            self.process_command_line_settings(kwargs)
        #end if

        write_splash()

        # print version information
        self.nxs_print("Checking current machine for Nexus dependencies...\n")
        pkg_sort = {
            "numpy":      0,
            "scipy":      1,
            "h5py":       2,
            "matplotlib": 3,
            "spglib":     4,
            "cif2cell":   5,
            "pydot":      6,
            "seekpath":   7,
            }

        try:
            nxs_requirements = importlib.metadata.requires("nexus")
            nxs_deps = {}
            for req in nxs_requirements:
                pkg_name = req.split("=")[0][:-1]
                pkg_ver_min = req.split(">=")[-1]
                if ";" in pkg_ver_min:
                    pkg_ver_min = pkg_ver_min.split(";")[0]
                    status = "optional"
                else:
                    status = "required"

                nxs_deps[pkg_name] = {"min_ver": pkg_ver_min, "status": status}
        except PackageNotFoundError:
            nxs_deps = {
                "numpy":      {"min_ver": "x.x.x", "status": "required"},
                "scipy":      {"min_ver": "x.x.x", "status": "optional"},
                "h5py":       {"min_ver": "x.x.x", "status": "optional"},
                "matplotlib": {"min_ver": "x.x.x", "status": "optional"},
                "spglib":     {"min_ver": "x.x.x", "status": "optional"},
                "cif2cell":   {"min_ver": "x.x.x", "status": "optional"},
                "pydot":      {"min_ver": "x.x.x", "status": "optional"},
                "seekpath":   {"min_ver": "x.x.x", "status": "optional"},
                }

        nxs_deps = {k:v for k, v in sorted(nxs_deps.items(), key=lambda x: pkg_sort.get(x[0], 1000))}

        available_pkgs = {}
        for module in nxs_deps.keys():
            if importlib.util.find_spec(module) is not None:
                available_pkgs[module] = importlib.metadata.version(module)
            else:
                available_pkgs[module] = "Unavailable"

        version_text = ""

        name_align = max([len(i) for i in nxs_deps.keys()])
        version_text +=  "  Currently Available Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} = {sys.version.split()[0]}\n"
        for pkg_name, pkg_ver in available_pkgs.items():
            version_text += f"    {pkg_name:<{name_align}} = {pkg_ver:<11} ({nxs_deps[pkg_name]['status']})\n"

        version_text +=  "\n"
        version_text +=  "  Recommended Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} >= 3.10.0\n"
        for pkg_name, pkg_info in nxs_deps.items():
            version_text += f"    {pkg_name:<{name_align}} >= {pkg_info['min_ver']:<10} ({pkg_info['status']})\n"

        version_text += "\n"
        missing_deps = set(nxs_deps) - set([i for i, a in available_pkgs.items() if a != "Unavailable"])
        if len(missing_deps) > 0:
            version_text += "  Required dependencies are met,\n"
            version_text += "  however some optional dependencies are missing.\n"
            version_text += "  Some features of Nexus may be unavailable.\n\n"

            version_text += "  Missing dependencies:\n"
            for missing in missing_deps:
                version_text += f"    - {missing} ({nxs_deps[pkg_name]['status']})\n"
        else:
            version_text += "  All dependencies are present.\n"

        version_text += "\n"

        self.nxs_print(version_text)

        self.nxs_print('Applying user settings')

        # assign simple variables
        for name in Settings.core_assign_vars:
            if name in kwargs:
                nexus_core[name] = kwargs[name]
            #end if
        #end for

        # assign simple variables
        for name in Settings.noncore_assign_vars:
            if name in kwargs:
                nexus_noncore[name] = kwargs[name]
            #end if
        #end for

        # extract settings based on keyword groups
        kw        = Settings.kw_set(Settings.nexus_vars     ,kwargs)
        mach_kw   = Settings.kw_set(Settings.machine_vars   ,kwargs)
        gamess_kw = Settings.kw_set(Settings.gamess_vars    ,kwargs)
        pwscf_kw  = Settings.kw_set(Settings.pwscf_vars     ,kwargs)
        qm_pkg_kw = Settings.kw_set(Settings.qm_package_vars,kwargs)
        if len(kwargs)>0:
            msg = f'some settings keywords have not been accounted for\nleftover keywords: {sorted(kwargs.keys())}\nthis is a developer error'
            raise NexusError(msg)
        #end if


        # copy input settings
        self.update(**deepcopy(mach_kw))
        self.update(**deepcopy(gamess_kw))
        self.update(**deepcopy(pwscf_kw))

        # process machine settings
        self.process_machine_settings(mach_kw)

        # process nexus core settings
        self.process_core_settings(kw)

        # process nexus noncore settings
        self.process_noncore_settings(kw)

        # transfer select core data to the global namespace
        for k in nexus_core_noncore.keys():
            nexus_core_noncore[k] = nexus_core[k]
        nexus_noncore.update(**deepcopy(nexus_core_noncore)) # prevent write to core namespace

        # copy final core and noncore settings
        self.update(**deepcopy(nexus_core))
        self.update(**deepcopy(nexus_noncore))


        # process gamess settings
        Gamess.restore_default_settings()
        Gamess.settings(**gamess_kw)

        # process pwscf settings
        Pwscf.restore_default_settings()
        Pwscf.settings(**pwscf_kw)

        # process quantum package settings
        QuantumPackage.restore_default_settings()
        QuantumPackage.settings(**qm_pkg_kw)

        return
    #end def __call__


    def process_command_line_settings(self,script_settings):
        from optparse import OptionParser
        usage = '''usage: %prog [options]'''
        version = '{}.{}.{}'.format(*nexus_version)
        parser = OptionParser(usage=usage,add_help_option=True,version='%prog '+version)

        parser.add_option('--status_only',dest='status_only',
                        action='store_true',default=False,
                        help='Report status of all simulations and then exit.'
                        )
        parser.add_option('--status',dest='status',
                        default='none',
                        help="Controls displayed simulation status information.  May be set to one of 'standard', 'active', 'failed', or 'ready'."
                        )
        parser.add_option('--generate_only',dest='generate_only',
                        action='store_true',default=False,
                        help='Write inputs to all simulations and then exit.  Note that no dependencies are processed, e.g. if one simulation depends on another for an orbital file location or for a relaxed structure, this information will not be present in the generated input file for that simulation since no simulations are actually run with this option.'
                        )
        parser.add_option('--graph_sims',dest='graph_sims',
                        action='store_true',default=False,
                        help='Display a graph of simulation workflows, then exit.'
                        )
        parser.add_option('--progress_tty',dest='progress_tty',
                        action='store_true',default=False,
                        help='Print abbreviated polling messages.'
                        )
        parser.add_option('--sleep',dest='sleep',
                        default='none',
                        help=f'Number of seconds between polls.  At each poll, simulations are actually run provided all simulations they depend on have successfully completed (default={nexus_core_defaults.sleep}).'
                        )
        parser.add_option('--timeout',dest='timeout',
                        default='none',
                        help=f'Number of seconds to wait for output and error files after a job exits the queue before marking the simulation as failed (default={nexus_core_defaults.timeout}).'
                        )
        parser.add_option('--machine',dest='machine',
                        default='none',
                        help="(Required) Name of the machine the simulations will be run on.  Workstations with between 1 and 128 cores may be specified by 'ws1' to 'ws128' (works for any machine where only mpirun is used).  For a complete listing of currently available machines (including those at HPC centers) please see the manual."
                        )
        parser.add_option('--account',dest='account',
                        default='none',
                        help='Account name required to submit jobs at some HPC centers.'
                        )
        parser.add_option('--runs',dest='runs',
                        default='none',
                        help=f'Directory to perform all runs in.  Simulation paths are appended to this directory (default={nexus_core_defaults.runs}).'
                        )
        parser.add_option('--results',dest='results',
                        default='none',
                        help=f"Directory to copy out lightweight results data.  If set to '', results will not be stored outside of the runs directory (default={nexus_core_defaults.results})."
                        )
        parser.add_option('--local_directory',dest='local_directory',
                        default='none',
                        help=f'Base path where runs and results directories will be created (default={nexus_core_defaults.local_directory}).'
                        )
        parser.add_option('--pseudo_dir',dest='pseudo_dir',
                        default='none',
                        help='Path to directory containing pseudopotential files (required if running with pseudopotentials).'
                        )
        parser.add_option('--basis_dir',dest='basis_dir',
                        default='none',
                        help='Path to directory containing basis set files (useful if running gaussian based QMC workflows).'
                        )
        parser.add_option('--ericfmt',dest='ericfmt',
                        default='none',
                        help='Path to the ericfmt file used with GAMESS (required if running GAMESS).'
                        )
        parser.add_option('--mcppath',dest='mcppath',
                        default='none',
                        help='Path to the mcpdata file used with GAMESS (optional for most workflows)'
                        )
        parser.add_option('--vdw_table',dest='vdw_table',
                        default='none',
                        help='Path to the vdw_table file used with Quantum Espresso (required only if running Quantum Espresso with van der Waals functionals).'
                        )
        parser.add_option('--qprc',dest='qprc',
                        default='none',
                        help='Path to the quantum_package.rc file used with Quantum Package.'
                        )

        # parse the command line inputs
        options,files_in = parser.parse_args()
        opt = obj(**options.__dict__)

        # check that all options are allowed (developer check)
        invalid = set(opt.keys())-Settings.allowed_vars
        if len(invalid)>0:
            msg = f'invalid command line settings encountered\ninvalid settings: {sorted(invalid)}\nthis is a developer error'
            raise NexusError(msg)
        #end if

        # pre-process options, full processing occurs upon return
        boolean_options = set(['status_only','generate_only','progress_tty'])
        real_options = {'sleep', 'timeout'}
        for ropt in real_options:
            if opt[ropt]!='none':
                try:
                    opt[ropt] = float(opt[ropt])
                except:
                    msg = f"command line option '{ropt}' must be a real value\nyou provided: {opt[ropt]}\nplease try again"
                    raise ValueError(msg)
                #end try
            #end if
        #end for

        # override script settings with command line settings
        for name,value in opt.items():
            bool_name = name in boolean_options
            if (bool_name and value) or (not bool_name and value!='none'):
                script_settings[name] = value
            #end if
        #end for

    #end def process_command_line_settings


    def process_machine_settings(self,mset):
        Job.restore_default_settings()
        ProjectManager.restore_default_settings()
        mid_set = set()
        if 'machine_info' in mset:
            machine_info = mset.machine_info
            if isinstance(machine_info,dict) or isinstance(machine_info,obj):
                for machine_name,minfo in machine_info.items():
                    mname = machine_name.lower()
                    if Machine.exists(mname):
                        machine = Machine.get(mname)
                        machine.restore_default_settings()
                        machine.incorporate_user_info(minfo)
                        mid_set.add(id(machine))
                    else:
                        msg = f'machine {machine_name} is unknown\n  cannot set machine_info'
                        raise ValueError(msg)
                    #end if
                #end for
            else:
                msg = 'machine_info must be a dict or obj\n  you provided type '+machine_info.__class__.__name__
                raise TypeError(msg)
            #end if
        #end if
        if 'machine' in mset:
            machine_name = mset.machine
            if machine_name in {"ws", "workstation"}:
                self.nxs_print("Automatically detecting physical CPU cores for workstation...", n=1)
                n_cores = get_cpu_cores()
                self.nxs_print(f"Using {n_cores} core workstation", n=1)
                machine_name = f"ws{n_cores}"

                if not Machine.exists(machine_name):
                    # Register a workstation with the determined number of cores
                    # if there is not already one that exists.
                    Workstation(machine_name, n_cores, 'mpirun')

            if not Machine.exists(machine_name):
                msg = f'machine {machine_name} is unknown'
                raise ValueError(msg)
            #end if
            Job.machine = machine_name
            machine = Machine.get(machine_name)
            ProjectManager.machine = machine
            if machine is not None and id(machine) not in mid_set:
                machine.restore_default_settings()
            #end if
            if 'account' in mset:
                account = mset.account
                if not isinstance(account,str):
                    msg = f'account for {machine_name} must be a string\nyou provided: {account}'
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.account = account
            #end if
            if 'user' in mset:
                user = mset.user
                if not isinstance(user,str):
                    msg = f'user for {machine_name} must be a string\nyou provided: {user}'
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.user = user
            #end if
            if 'machine_mode' in mset:
                machine_mode = mset.machine_mode
                if machine_mode in Machine.modes:
                    machine_mode = Machine.modes[machine_mode]
                #end if
                if machine_mode==Machine.modes.interactive:
                    if ProjectManager.machine is None:
                        msg = 'no machine specified for interactive mode'
                        raise ValueError(msg)
                    #end if
                    if not isinstance(ProjectManager.machine,Supercomputer):
                        msg = 'interactive mode is not supported for machine type '+ProjectManager.machine.__class__.__name__
                        raise NotImplementedError(msg)
                    #end if
                    if 'interactive_cores' not in mset:
                        msg = 'interactive mode requested, but interactive_cores not set'
                        raise ValueError(msg)
                    #end if
                    ProjectManager.machine = ProjectManager.machine.interactive_representation(mset.interactive_cores)
                    Job.machine = ProjectManager.machine.name
                #end if
            #end if
        #end if
    #end def process_machine_settings


    def process_core_settings(self,kw):
        # process project manager settings
        if nexus_core.debug:
            nexus_core.verbose = True
        #end if
        if 'status' in kw:
            if kw.status==None or kw.status==False:
                nexus_core.status = nexus_core.status_modes.none
            elif kw.status==True:
                nexus_core.status = nexus_core.status_modes.standard
            elif kw.status in nexus_core.status_modes:
                nexus_core.status = nexus_core.status_modes[kw.status]
            else:
                msg = f'invalid status mode specified: {kw.status}\nvalid status modes are: {sorted(nexus_core.status_modes.keys())}'
                raise ValueError(msg)
            #end if
        #end if
        if nexus_core.status_only and nexus_core.status==nexus_core.status_modes.none:
            nexus_core.status = nexus_core.status_modes.standard
        #end if
        if 'mode' in kw:
            if kw.mode in nexus_core.modes:
                nexus_core.mode = kw.mode
            else:
                msg = f'invalid mode specified: {kw.mode}\nvalid modes are: {sorted(nexus_core.modes.keys())}'
                raise ValueError(msg)
            #end if
        #end if
        mode  = nexus_core.mode
        modes = nexus_core.modes
        if mode==modes.stages:
            stages = nexus_core.stages
        elif mode==modes.all:
            stages = list(nexus_core.primary_modes)
        else:
            stages = [kw.mode]
        #end if
        allowed_stages = set(nexus_core.primary_modes)
        if isinstance(stages,str):
            stages = [stages]
        #end if
        if len(stages)==0:
            stages = list(nexus_core.primary_modes)
        elif 'all' in stages:
            stages = list(nexus_core.primary_modes)
        else:
            forbidden = set(nexus_core.stages)-allowed_stages
            if len(forbidden)>0:
                msg = 'some stages provided are not primary stages.\n  You provided '+str(list(forbidden))+'\n  Options are '+str(list(allowed_stages))
                raise ValueError(msg)
            #end if
        #end if
        # overide user input and always use stages mode
        # keep processing code above in case a change is desired in the future
        nexus_core.mode       = modes.stages
        nexus_core.stages     = stages
        nexus_core.stages_set = set(nexus_core.stages)

        # process simulation settings
        if 'local_directory' in kw:
            nexus_core.file_locations.append(kw.local_directory)
        #end if
        if 'file_locations' in kw:
            fl = kw.file_locations
            if isinstance(fl,str):
                nexus_core.file_locations.extend([path_string(fl)])
            else:
                nexus_core.file_locations.extend([path_string(f) for f in fl])
            #end if
        #end if
        pseudo_dir = kw.get('pseudo_dir',None)
        if pseudo_dir is not None:
            if not os.path.isdir(pseudo_dir):
                msg = f'pseudo_dir "{pseudo_dir}" does not exist or is not a directory'
                raise NotADirectoryError(msg)
            #end if
            pseudo_dir = os.path.abspath(pseudo_dir)
            nexus_core.pseudo_dir = pseudo_dir
        #end if
        PseudoSet.pseudo_files.clear()
        PseudoSet.labeled_pseudosets.clear()
        if pseudo_dir is not None:
            for file in Path(pseudo_dir).iterdir():
                if file.is_file():
                    PseudoSet.pseudo_files[file.name] = str(file.resolve())
                #end if
            #end for
        #end if

        # backwards compatibility with prior results_dir default
        old_results_default = 'results'
        old_results_dir = os.path.join(nexus_core.local_directory,old_results_default)
        if 'results' not in kw and os.path.exists(old_results_dir):
            nexus_core.results = old_results_default
        #end if
    #end def process_core_settings


    def process_noncore_settings(self,kw):
        if 'basis_dir' not in kw:
            nexus_noncore.basissets = BasisSets()
        else:
            basis_dir = kw.basis_dir
            nexus_core.file_locations.append(basis_dir)
            if not os.path.exists(basis_dir):
                msg = f'basis_dir "{basis_dir}" does not exist'
                raise FileNotFoundError(msg)
            #end if
            files = os.listdir(basis_dir)
            bsfiles = []
            for f in files:
                pf = os.path.join(basis_dir,f)
                if os.path.isfile(pf):
                    bsfiles.append(pf)
                #end if
            #end for
            nexus_noncore.basissets = BasisSets(bsfiles)
        #end if
    #end def process_noncore_settings
#end class Settings


# create settings functor for UI
settings = Settings()
