##################################################################
##  (c) Copyright 2015-  by Jaron T. Krogel                     ##
##################################################################


#====================================================================#
#  nexus.py                                                          #
#    Gathering place for user-facing Nexus functions.  Management    #
#    of user-provided settings.                                      #
#                                                                    #
#  Content summary:                                                  #
#    Settings                                                        #
#      Class to set 'global' Nexus data.                             #
#                                                                    #
#    settings                                                        #
#      A single Settings instance users interact with as a function. #
#                                                                    #
#    run_project                                                     #
#      User interface to the ProjectManager.                         #
#      Runs all simulations generated by the user.                   #
#                                                                    #
#====================================================================#

import os
import sys
from copy import deepcopy
import importlib
from importlib.metadata import PackageNotFoundError
from pathlib import Path
from collections.abc import Collection

from .nexus_version import nexus_version
from .generic       import generic_settings
from .developer     import obj, log, NexusError, warn
from .debug         import ci
from .utilities     import path_string

from .nexus_base      import NexusCore, NexusConfig, SimStage, ShowStatusMode, NEXUS_CONFIG, write_splash
from .machines        import Job,                    job,            Machine, Supercomputer, get_machine, get_cpu_cores, Workstation
from .simulation      import generate_simulation,    input_template, multi_input_template,   generate_template_input,    generate_multi_template_input,  graph_sims, DynamicProcess
from .project_manager import ProjectManager,     DynamicWorkflowManager,     workflow_manager

from .structure       import Structure,          generate_structure,         generate_cell,  read_structure
from .physical_system import PhysicalSystem,     generate_physical_system
from .pseudopotential import Pseudopotential
from .pseudoset       import PseudoSet, ppset, generate_pseudoset
from .basisset        import BasisSets
from .bundle          import bundle

from .pwscf   import Pwscf  , PwscfInput  , PwscfAnalyzer  , generate_pwscf_input  , generate_pwscf
from .gamess  import Gamess , GamessInput , GamessAnalyzer , generate_gamess_input , generate_gamess, FormattedGroup
from .vasp    import Vasp   , VaspInput   , VaspAnalyzer   , generate_vasp_input   , generate_vasp
from .qmcpack import Qmcpack, QmcpackInput, QmcpackAnalyzer, generate_qmcpack_input, generate_qmcpack
from .quantum_package import QuantumPackage,QuantumPackageInput,QuantumPackageAnalyzer,generate_quantum_package_input,generate_quantum_package
from .pyscf_sim import Pyscf, PyscfInput, PyscfAnalyzer, generate_pyscf_input, generate_pyscf
from .rmg import Rmg, RmgInput, RmgAnalyzer, generate_rmg_input, generate_rmg

from .qmcpack_converters import Pw2qmcpack , Pw2qmcpackInput , Pw2qmcpackAnalyzer , generate_pw2qmcpack_input , generate_pw2qmcpack
from .qmcpack_converters import Convert4qmc, Convert4qmcInput, Convert4qmcAnalyzer, generate_convert4qmc_input, generate_convert4qmc
from .qmcpack_converters import Convertpw4qmc, Convertpw4qmcInput, Convertpw4qmcAnalyzer, generate_convertpw4qmc_input, generate_convertpw4qmc
from .qmcpack_converters import PyscfToAfqmc, PyscfToAfqmcInput, PyscfToAfqmcAnalyzer, generate_pyscf_to_afqmc_input, generate_pyscf_to_afqmc

from .pwscf_postprocessors import PP      , PPInput      , PPAnalyzer      , generate_pp_input      , generate_pp
from .pwscf_postprocessors import Dos     , DosInput     , DosAnalyzer     , generate_dos_input     , generate_dos
from .pwscf_postprocessors import Bands   , BandsInput   , BandsAnalyzer   , generate_bands_input   , generate_bands
from .pwscf_postprocessors import Projwfc , ProjwfcInput , ProjwfcAnalyzer , generate_projwfc_input , generate_projwfc
from .pwscf_postprocessors import Cppp    , CpppInput    , CpppAnalyzer    , generate_cppp_input    , generate_cppp
from .pwscf_postprocessors import Pwexport, PwexportInput, PwexportAnalyzer, generate_pwexport_input, generate_pwexport
from .pwscf_postprocessors import Hp      , HpInput      , HpAnalyzer      , generate_hp_input      , generate_hp

from .qmcpack import loop,linear,cslinear,vmc,dmc
from .qmcpack import generate_jastrows,generate_jastrow,generate_jastrow1,generate_jastrow2,generate_jastrow3,generate_opt,generate_opts
from .qmcpack import generate_cusp_correction


#set the machine if known, otherwise user will provide
hostmachine = Machine.get_hostname()
if Machine.exists(hostmachine):
    Job.machine = hostmachine
    ProjectManager.machine = Machine.get(hostmachine)
#end if


# test needed
def run_project(*args,**kwargs):
    if NEXUS_CONFIG.graph_sims:
        graph_sims()
    #end if
    pm = ProjectManager()
    pm.add_simulations(*args,**kwargs)
    pm.run_project()
    return pm
#end def run_project


# test needed
# read input function
#   place here for now as it depends on all other input functions
def read_input(filepath,format=None):
    if not os.path.exists(filepath):
        msg = f'cannot read input file\nfile does not exist: {filepath}'
        raise FileNotFoundError(msg)
    #end if
    if format is None:
        if filepath.endswith('in.xml'):
            format = 'qmcpack'
        else:
            msg = f'cannot identify file format\nplease provide format for file: {filepath}'
            raise RuntimeError(msg)
        #end if
    #end if
    format = format.lower()
    if format=='qmcpack':
        input = QmcpackInput(filepath)
    elif format=='pwscf':
        input = PwscfInput(filepath)
    elif format=='gamess':
        input = GamessInput(filepath)
    else:
        msg = f'cannot read input file\nfile format "{format}" is unsupported'
        raise NotImplementedError(msg)
    #end if
    return input
#end def read_input



class Settings(NexusCore):
    singleton = None

    machine_vars = frozenset({
        'interactive_cores', 'machine_info', 'machine', 'machine_mode', 'user', 'account'
        })

    gamess_vars  = frozenset({'ericfmt', 'mcppath'})

    pwscf_vars   = frozenset({'vdw_table'})

    qm_package_vars = frozenset({'qprc'})

    nexus_vars         = frozenset(NexusConfig.__slots__)
    allowed_vars       = nexus_vars | machine_vars \
                    | gamess_vars | pwscf_vars | qm_package_vars


    @staticmethod
    def kw_set(vars,source=None):
        kw = obj()
        if source is not None:
            for n in vars:
                if n in source:
                    kw[n]=source[n]
                    del source[n]
                #end if
            #end for
        #end if
        return kw
    #end def null_kw_set


    def __init__(self):
        if Settings.singleton is None:
            Settings.singleton = self
        else:
            msg = 'attempted to create a second Settings object\nplease just use the original'
            raise RuntimeError(msg)
        #end if
    #end def __init__


    # sets up Nexus core class behavior and passes information to broader class structure
    def __call__(self,**kwargs):
        kwargs = obj(**kwargs)
        # Ensure no pathlib.Path objects are stored
        core_path_vars = (
            "runs",
            "results",
            "pseudo_dir",
            "local_directory",
            "remote_directory",
            )
        for var in core_path_vars:
            if var in kwargs:
                kwargs[var] = path_string(kwargs[var])

        # guard against invalid settings
        not_allowed = set(kwargs.keys()) - Settings.allowed_vars
        if len(not_allowed)>0:
            msg = f'unrecognized variables provided\nyou provided: {sorted(not_allowed)}\nallowed variables are: {sorted(Settings.allowed_vars)}'
            raise ValueError(msg)
        #end if

        # restore default core default settings
        NEXUS_CONFIG.restore_defaults()

        # process command line inputs, if any
        if 'command_line' in kwargs:
            NEXUS_CONFIG.command_line = kwargs.command_line
        #end if
        if NEXUS_CONFIG.command_line:
            self.process_command_line_settings(kwargs)
        #end if

        write_splash()

        # print version information
        self.log("Checking current machine for Nexus dependencies...\n")
        pkg_sort = {
            "numpy":      0,
            "scipy":      1,
            "h5py":       2,
            "matplotlib": 3,
            "spglib":     4,
            "cif2cell":   5,
            "pydot":      6,
            "seekpath":   7,
            }

        try:
            nxs_requirements = importlib.metadata.requires("nexus")
            nxs_deps = {}
            for req in nxs_requirements:
                pkg_name = req.split("=")[0][:-1]
                pkg_ver_min = req.split(">=")[-1]
                if ";" in pkg_ver_min:
                    pkg_ver_min = pkg_ver_min.split(";")[0]
                    status = "optional"
                else:
                    status = "required"

                nxs_deps[pkg_name] = {"min_ver": pkg_ver_min, "status": status}
        except PackageNotFoundError:
            nxs_deps = {
                "numpy":      {"min_ver": "x.x.x", "status": "required"},
                "scipy":      {"min_ver": "x.x.x", "status": "optional"},
                "h5py":       {"min_ver": "x.x.x", "status": "optional"},
                "matplotlib": {"min_ver": "x.x.x", "status": "optional"},
                "spglib":     {"min_ver": "x.x.x", "status": "optional"},
                "cif2cell":   {"min_ver": "x.x.x", "status": "optional"},
                "pydot":      {"min_ver": "x.x.x", "status": "optional"},
                "seekpath":   {"min_ver": "x.x.x", "status": "optional"},
                }

        nxs_deps = {k:v for k, v in sorted(nxs_deps.items(), key=lambda x: pkg_sort.get(x[0], 1000))}

        available_pkgs = {}
        for module in nxs_deps:
            if importlib.util.find_spec(module) is not None:
                available_pkgs[module] = importlib.metadata.version(module)
            else:
                available_pkgs[module] = "Unavailable"

        version_text = ""

        name_align = max([len(i) for i in nxs_deps])
        version_text +=  "  Currently Available Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} = {sys.version.split()[0]}\n"
        for pkg_name, pkg_ver in available_pkgs.items():
            version_text += f"    {pkg_name:<{name_align}} = {pkg_ver:<11} ({nxs_deps[pkg_name]['status']})\n"

        version_text +=  "\n"
        version_text +=  "  Recommended Nexus Dependencies:\n"
        version_text += f"    {'Python':<{name_align}} >= 3.10.0\n"
        for pkg_name, pkg_info in nxs_deps.items():
            version_text += f"    {pkg_name:<{name_align}} >= {pkg_info['min_ver']:<10} ({pkg_info['status']})\n"

        version_text += "\n"
        missing_deps = set(nxs_deps) - {i for i, a in available_pkgs.items() if a != "Unavailable"}
        if len(missing_deps) > 0:
            version_text += "  Required dependencies are met,\n"
            version_text += "  however some optional dependencies are missing.\n"
            version_text += "  Some features of Nexus may be unavailable.\n\n"

            version_text += "  Missing dependencies:\n"
            for missing in missing_deps:
                version_text += f"    - {missing} ({nxs_deps[pkg_name]['status']})\n"
        else:
            version_text += "  All dependencies are present.\n"

        version_text += "\n"

        self.log(version_text)

        self.log('Applying user settings')

        # extract settings based on keyword groups
        kw        = Settings.kw_set(Settings.nexus_vars     ,kwargs)
        mach_kw   = Settings.kw_set(Settings.machine_vars   ,kwargs)
        gamess_kw = Settings.kw_set(Settings.gamess_vars    ,kwargs)
        pwscf_kw  = Settings.kw_set(Settings.pwscf_vars     ,kwargs)
        qm_pkg_kw = Settings.kw_set(Settings.qm_package_vars,kwargs)
        if len(kwargs)>0:
            msg = (
                'Some settings keywords have not been accounted for\n'
                f'Leftover keywords: {sorted(kwargs.keys())}\n'
                'This is a developer error'
            )
            raise NexusError(msg)
        #end if


        # copy input settings
        self.update(**deepcopy(mach_kw))
        self.update(**deepcopy(gamess_kw))
        self.update(**deepcopy(pwscf_kw))

        # process machine settings
        self.process_machine_settings(mach_kw)

        # process nexus config settings
        self.process_config_settings(kw)

        # process gamess settings
        Gamess.restore_default_settings()
        Gamess.settings(**gamess_kw)

        # process pwscf settings
        Pwscf.restore_default_settings()
        Pwscf.settings(**pwscf_kw)

        # process quantum package settings
        QuantumPackage.restore_default_settings()
        QuantumPackage.settings(**qm_pkg_kw)
    #end def __call__


    def process_command_line_settings(self,script_settings):
        from optparse import OptionParser
        usage = '''usage: %prog [options]'''
        version = '{}.{}.{}'.format(*nexus_version)
        parser = OptionParser(usage=usage,add_help_option=True,version='%prog '+version)

        parser.add_option('--status_only',dest='status_only',
                        action='store_true',default=False,
                        help='Report status of all simulations and then exit.'
                        )
        parser.add_option('--status',dest='status',
                        default='none',
                        help="Controls displayed simulation status information.  May be set to one of 'standard', 'active', 'failed', or 'ready'."
                        )
        parser.add_option('--generate_only',dest='generate_only',
                        action='store_true',default=False,
                        help='Write inputs to all simulations and then exit.  Note that no dependencies are processed, e.g. if one simulation depends on another for an orbital file location or for a relaxed structure, this information will not be present in the generated input file for that simulation since no simulations are actually run with this option.'
                        )
        parser.add_option('--graph_sims',dest='graph_sims',
                        action='store_true',default=False,
                        help='Display a graph of simulation workflows, then exit.'
                        )
        parser.add_option('--progress_tty',dest='progress_tty',
                        action='store_true',default=False,
                        help='Print abbreviated polling messages.'
                        )
        parser.add_option('--sleep',dest='sleep',
                        default='none',
                        help=f'Number of seconds between polls.  At each poll, simulations are actually run provided all simulations they depend on have successfully completed (default={NEXUS_CONFIG.sleep}).'
                        )
        parser.add_option('--timeout',dest='timeout',
                        default='none',
                        help=f'Number of seconds to wait for output and error files after a job exits the queue before marking the simulation as failed (default={NEXUS_CONFIG.timeout}).'
                        )
        parser.add_option('--machine',dest='machine',
                        default='none',
                        help="(Required) Name of the machine the simulations will be run on.  Workstations with between 1 and 128 cores may be specified by 'ws1' to 'ws128' (works for any machine where only mpirun is used).  For a complete listing of currently available machines (including those at HPC centers) please see the manual."
                        )
        parser.add_option('--account',dest='account',
                        default='none',
                        help='Account name required to submit jobs at some HPC centers.'
                        )
        parser.add_option('--runs',dest='runs',
                        default='none',
                        help=f'Directory to perform all runs in.  Simulation paths are appended to this directory (default={NEXUS_CONFIG.runs}).'
                        )
        parser.add_option('--results',dest='results',
                        default='none',
                        help=f"Directory to copy out lightweight results data.  If set to '', results will not be stored outside of the runs directory (default={NEXUS_CONFIG.results})."
                        )
        parser.add_option('--local_directory',dest='local_directory',
                        default='none',
                        help=f'Base path where runs and results directories will be created (default={NEXUS_CONFIG.local_directory}).'
                        )
        parser.add_option('--pseudo_dir',dest='pseudo_dir',
                        default='none',
                        help='Path to directory containing pseudopotential files (required if running with pseudopotentials).'
                        )
        parser.add_option('--basis_dir',dest='basis_dir',
                        default='none',
                        help='Path to directory containing basis set files (useful if running gaussian based QMC workflows).'
                        )
        parser.add_option('--ericfmt',dest='ericfmt',
                        default='none',
                        help='Path to the ericfmt file used with GAMESS (required if running GAMESS).'
                        )
        parser.add_option('--mcppath',dest='mcppath',
                        default='none',
                        help='Path to the mcpdata file used with GAMESS (optional for most workflows)'
                        )
        parser.add_option('--vdw_table',dest='vdw_table',
                        default='none',
                        help='Path to the vdw_table file used with Quantum Espresso (required only if running Quantum Espresso with van der Waals functionals).'
                        )
        parser.add_option('--qprc',dest='qprc',
                        default='none',
                        help='Path to the quantum_package.rc file used with Quantum Package.'
                        )

        # parse the command line inputs
        options,files_in = parser.parse_args()
        opt = obj(**options.__dict__)

        # check that all options are allowed (developer check)
        invalid = set(opt.keys())-Settings.allowed_vars
        if len(invalid)>0:
            msg = (
                'Invalid command line settings encountered\n'
                f'Invalid settings: {sorted(invalid)}\n'
                'This is a developer error'
                )
            raise NexusError(msg)
        #end if

        # pre-process options, full processing occurs upon return
        boolean_options = {'status_only','generate_only','progress_tty'}
        real_options = {'sleep', 'timeout'}
        for ropt in real_options:
            if opt[ropt]!='none':
                try:
                    opt[ropt] = float(opt[ropt])
                except ValueError as err:
                    msg = (
                        f"Command line option '{ropt}' must be a real value\n"
                        f"You provided: {opt[ropt]}\n"
                        "Please try again"
                        )
                    raise TypeError(msg) from err
                #end try
            #end if
        #end for

        # override script settings with command line settings
        for name,value in opt.items():
            bool_name = name in boolean_options
            if (bool_name and value) or (not bool_name and value!='none'):
                script_settings[name] = value
            #end if
        #end for
    #end def process_command_line_settings


    def process_machine_settings(self,mset):
        Job.restore_default_settings()
        ProjectManager.restore_default_settings()
        mid_set = set()
        if 'machine_info' in mset:
            machine_info = mset.machine_info
            if isinstance(machine_info, dict | obj):
                for machine_name,minfo in machine_info.items():
                    mname = machine_name.lower()
                    if Machine.exists(mname):
                        machine = Machine.get(mname)
                        machine.restore_default_settings()
                        machine.incorporate_user_info(minfo)
                        mid_set.add(id(machine))
                    else:
                        msg = (
                            f'machine {machine_name} is unknown\n'
                            '  cannot set machine_info'
                            )
                        raise ValueError(msg)
                    #end if
                #end for
            else:
                msg = (
                    'machine_info must be a dict or obj\n'
                    '  you provided type '+type(machine_info).__name__
                    )
                raise TypeError(msg)
            #end if
        #end if
        if 'machine' in mset:
            machine_name = mset.machine
            if machine_name in {"ws", "workstation"}:
                self.log("Automatically detecting physical CPU cores for workstation...", n=1)
                n_cores = get_cpu_cores()
                self.log(f"Using {n_cores} core workstation", n=1)
                machine_name = f"ws{n_cores}"

                if not Machine.exists(machine_name):
                    # Register a workstation with the determined number of cores
                    # if there is not already one that exists.
                    Workstation(machine_name, n_cores, 'mpirun')

            if not Machine.exists(machine_name):
                msg = f'machine {machine_name} is unknown'
                raise ValueError(msg)
            #end if
            Job.machine = machine_name
            machine = Machine.get(machine_name)
            ProjectManager.machine = machine
            if machine is not None and id(machine) not in mid_set:
                machine.restore_default_settings()
            #end if
            if 'account' in mset:
                account = mset.account
                if not isinstance(account,str):
                    msg = (
                        f'account for {machine_name} must be a string\n'
                        f'you provided: {account}'
                        )
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.account = account
            #end if
            if 'user' in mset:
                user = mset.user
                if not isinstance(user,str):
                    msg = (
                        f'user for {machine_name} must be a string\n'
                        f'you provided: {user}'
                        )
                    raise TypeError(msg)
                #end if
                ProjectManager.machine.user = user
            #end if
            if 'machine_mode' in mset:
                machine_mode = mset.machine_mode
                if machine_mode in Machine.modes:
                    machine_mode = Machine.modes[machine_mode]
                #end if
                if machine_mode==Machine.modes.interactive:
                    if ProjectManager.machine is None:
                        msg = 'no machine specified for interactive mode'
                        raise ValueError(msg)
                    #end if
                    if not isinstance(ProjectManager.machine,Supercomputer):
                        msg = 'interactive mode is not supported for machine type '+ProjectManager.machine.__class__.__name__
                        raise NotImplementedError(msg)
                    #end if
                    if 'interactive_cores' not in mset:
                        msg = 'interactive mode requested, but interactive_cores not set'
                        raise ValueError(msg)
                    #end if
                    ProjectManager.machine = ProjectManager.machine.interactive_representation(mset.interactive_cores)
                    Job.machine = ProjectManager.machine.name
                #end if
            #end if
        #end if
    #end def process_machine_settings


    def process_config_settings(self, kw: dict):
        # Deprecated variables
        deprecated = (
            ("mode", "Please use `stages` instead!"),
            ("verbose", "Please use `quiet` instead!"),
            ("debug", "This variable was redundant, please remove from your script!"),
            ("trace", "This variable was unused in Nexus, please remove from your script!"),
            ("emulate", "This variable was unused in Nexus, please remove from your script!"),
        )
        for var, extra in deprecated:
            if var in kw:
                del kw[var]
                warn(
                    f"The setting '{var}' has been deprecated!\n"
                    f"{extra}"
                    )

        match kw.pop("status", None):
            case None | False:
                pass
            case True:
                NEXUS_CONFIG.status = ShowStatusMode.ALL
            case val:
                val_str = str(val).upper()
                if val_str not in ShowStatusMode.__members__:
                    msg = (
                        f"Invalid status mode specified: {val}\n"
                        f"Valid status modes are: {[*ShowStatusMode.__members__]}"
                    )
                    raise ValueError(msg)
                NEXUS_CONFIG.status = ShowStatusMode[val_str]

        if status_only := kw.pop("status_only", None):
            NEXUS_CONFIG.status_only = status_only
            if NEXUS_CONFIG.status is ShowStatusMode.NONE:
                NEXUS_CONFIG.status = ShowStatusMode.ALL

        stages = kw.pop("stages", None)
        generate_only = kw.pop("generate_only", None)
        if stages is not None and generate_only is not None:
            msg = "Can not set both `stages` and `generate_only`!"
            raise ValueError(msg)
        elif isinstance(stages, SimStage):
            NEXUS_CONFIG.stages = stages
        elif isinstance(stages, str):
            if stages.upper() not in SimStage.__members__:
                msg = (
                    f"Invalid stages specified: {val}\n"
                    f"Valid stages are: {[*SimStage.__members__]}"
                )
                raise ValueError(msg)
            NEXUS_CONFIG.stages = SimStage[stages.upper()]
        elif isinstance(stages, Collection):
            NEXUS_CONFIG.stages = SimStage.from_list(stages)
        elif stages is not None:
            msg = f"stages should be a SimStage, str, or list of str, but is {type(stages)}!"
            raise TypeError(msg)
        elif generate_only:
            NEXUS_CONFIG.stages = SimStage.SETUP # Preferred new route
            NEXUS_CONFIG.generate_only = True # Legacy, will replace

        if (loc_dir := kw.pop("local_directory", None)) is not None:
            NEXUS_CONFIG.file_locations.append(loc_dir)

        if (file_locs := kw.pop("file_locations", None)) is not None:
            if isinstance(file_locs, str | Path):
                NEXUS_CONFIG.file_locations.append(path_string(file_locs))
            else:
                NEXUS_CONFIG.file_locations.extend(
                    path_string(i) for i in file_locs
                )

        if (pseudo_dir := kw.pop("pseudo_dir", None)) is not None:
            pseudo_dir = Path(pseudo_dir).resolve(strict=True)
            if not pseudo_dir.is_dir():
                msg = f"pseudo_dir '{pseudo_dir}' is not a directory!"
                raise NotADirectoryError(msg)

            NEXUS_CONFIG.pseudo_dir = path_string(pseudo_dir)

        PseudoSet.pseudo_files.clear()
        PseudoSet.labeled_pseudosets.clear()
        if NEXUS_CONFIG.pseudo_dir is not None:
            for file in Path(NEXUS_CONFIG.pseudo_dir).iterdir():
                if file.is_file():
                    PseudoSet.pseudo_files[file.name] = str(file)

        # backwards compatibility with prior results_dir default
        old_results_default = 'results'
        old_results_dir = os.path.join(NEXUS_CONFIG.local_directory,old_results_default)
        if 'results' not in kw and os.path.exists(old_results_dir):
            NEXUS_CONFIG.results = old_results_default

        if basis_dir := kw.pop("basis_dir", None):
            basis_dir = Path(basis_dir).resolve(strict=True)
            if not basis_dir.is_dir():
                msg = f"basis_dir '{basis_dir}' is not a directory!"
                raise NotADirectoryError(msg)

            NEXUS_CONFIG.file_locations.append(path_string(basis_dir))
            bs_files = []
            for file in basis_dir.iterdir():
                if file.is_file():
                    bs_files.append(path_string(file))

            NEXUS_CONFIG.basissets = BasisSets(bs_files)
        else:
            NEXUS_CONFIG.basissets = BasisSets()

        # Set remaining settings
        for cfg_var in NexusConfig.__slots__:
            if (cfg_val := kw.pop(cfg_var, None)) is not None:
                setattr(NEXUS_CONFIG, cfg_var, cfg_val)
    #end def process_core_settings
#end class Settings


# create settings functor for UI
settings = Settings()
