"""Module for storing input parameters for Quantum ESPRESSO.

The code in this module was auto-generated by a Python script that
uses the intermediate XML representation of QE's ``INPUT_PW.def`` files.

The script is at ``qmcpack/nexus/dev_utils/gen_pwscf_input_data.py``.

This module's code was autogenerated on Fri 24 Jul 2026, 11:36AM

The supported QE versions are v7.0.0-v7.6.0
"""

from __future__ import annotations
from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

PwscfInputType: TypeAlias = str | bool | int | float | Sequence
# For structured array inputs (k-points, weights, reciprocal lattice, etc.)
PwscfArrayInput: TypeAlias = Sequence[float | Sequence[float]]


@dataclass(frozen=True) # We generally don't want any of these to be modified
class NamelistParamDefinition:
    """Base class for all namelist variables."""

    datatype:        tuple[PwscfInputType]
    required:        bool
    shape:           tuple | None = None
    allowed_values:  tuple[PwscfInputType] | None = None
    version_added:   tuple[float] | None = None
    version_removed: tuple[float] | None = None
#end class NamelistDefinition


class NamelistEnumBase(Enum):
    """Abstract base class for the namelist enumerations.

    Provides the ``__new__`` method for the enums.
    """
    def __new__(
        cls,
        datatype:        PwscfInputType,
        required:        bool,
        allowed_values:  tuple[PwscfInputType] | None = None,
        version_added:   tuple[float] | None = None,
        version_removed: tuple[float] | None = None,
    ):
        definition = NamelistParamDefinition.__new__(cls)
        definition._value_ = NamelistParamDefinition(
            datatype,
            required,
            allowed_values,
            version_added,
            version_removed,
        )
        return definition
#end class NamelistEnumBase


class ControlDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &CONTROL input namelist for ``pw.x``."""

    #    name     = type, required, shape, allowed_values, v_added, v_removed
    calculation   = str,   False, None, ('scf', 'nscf', 'bands', 'relax', 'md', 'vc-relax', 'vc-md')
    title         = str,   False
    verbosity     = str,   False, None, ('high', 'low')
    restart_mode  = str,   False, None, ('from_scratch', 'restart')
    wf_collect    = bool,  False
    nstep         = int,   False
    iprint        = int,   False
    tstress       = bool,  False
    tprnfor       = bool,  False
    dt            = float, False
    outdir        = str,   False
    wfcdir        = str,   False
    prefix        = str,   False
    lkpoint_dir   = bool,  False
    max_seconds   = float, False
    etot_conv_thr = float, False
    forc_conv_thr = float, False
    disk_io       = str,   False, None, ('default', 'high', 'medium', 'low', 'nowf', 'minimal', 'none')
    pseudo_dir    = str,   False
    tefield       = bool,  False
    dipfield      = bool,  False
    lelfield      = bool,  False
    nberrycyc     = int,   False
    lorbm         = bool,  False
    lberry        = bool,  False
    gdir          = int,   False
    nppstr        = int,   False
    gate          = bool,  False
    twochem       = bool,  False, None, None, '7.2.0'
    lfcp          = bool,  False
    trism         = bool,  False, None, None, '7.1.0'
    #    name     = type, required, shape, allowed_values, v_added, v_removed
#end class ControlDefinitions


class SystemDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &SYSTEM input namelist for ``pw.x``."""

    #          name           = type, required, shape, allowed_values, v_added, v_removed
    ibrav                     = int,   True
    nat                       = int,   True
    ntyp                      = int,   True
    nbnd                      = int,   False
    nbnd_cond                 = int,   False, None, None, '7.2.0'
    tot_charge                = float, False
    tot_magnetization         = float, False
    ecutwfc                   = float, True
    ecutrho                   = float, False
    ecutfock                  = float, False
    nosym                     = bool,  False
    nosym_evc                 = bool,  False
    noinv                     = bool,  False
    no_t_rev                  = bool,  False
    force_symmorphic          = bool,  False
    use_all_frac              = bool,  False
    occupations               = str,   False, None, ('smearing', 'tetrahedra', 'tetrahedra_lin', 'tetrahedra_opt', 'fixed', 'from_input')
    one_atom_occupations      = bool,  False
    starting_spin_angle       = bool,  False
    degauss_cond              = float, False, None, None, '7.2.0'
    nelec_cond                = float, False, None, None, '7.2.0'
    degauss                   = float, False
    smearing                  = str,   False, None, ('gaussian', 'methfessel-paxton', 'marzari-vanderbilt', 'fermi-dirac', 'gauss', 'm-p', 'mp', 'cold', 'm-v', 'mv', 'f-d', 'fd')
    nspin                     = int,   False
    sic_gamma                 = float, False, None, None, '7.2.0'
    pol_type                  = str,   False, None, ('none', 'e', 'h'), '7.2.0'
    sic_energy                = bool,  False, None, None, '7.2.0'
    sci_vb                    = float, False, None, None, '7.2.0'
    sci_cb                    = float, False, None, None, '7.2.0'
    noncolin                  = bool,  False
    ecfixed                   = float, False
    qcutz                     = float, False
    q2sigma                   = float, False
    input_dft                 = str,   False
    ace                       = bool,  False
    exx_fraction              = float, False
    screening_parameter       = float, False
    exxdiv_treatment          = str,   False, None, ('gygi-baldereschi', 'vcut_spherical', 'vcut_ws', 'none')
    exx_type                  = str,   False, None, ('bands', 'band_pairs'), '7.6.0'
    x_gamma_extrapolation     = bool,  False
    ecutvcut                  = float, False
    localization_thr          = float, False
    dmft                      = bool,  False
    dmft_prefix               = str,   False
    ensemble_energies         = bool,  False
    edir                      = int,   False
    emaxpos                   = float, False
    eopreg                    = float, False
    eamp                      = float, False
    lforcet                   = bool,  False
    constrained_magnetization = str,   False, None, ('none', 'total', 'atomic', 'total direction', 'atomic direction')
    lambda_                   = float, False
    report                    = int,   False
    lspinorb                  = bool,  False
    assume_isolated           = str,   False, None, ('none', 'makov-payne', 'martyna-tuckerman', 'esm', '2D', 'm-p', 'mp', 'm-t', 'mt')
    esm_bc                    = str,   False, None, ('pbc', 'bc1', 'bc2', 'bc3')
    esm_w                     = float, False
    esm_efield                = float, False
    esm_nfit                  = int,   False
    lgcscf                    = bool,  False
    gcscf_mu                  = float, False
    gcscf_conv_thr            = float, False
    gcscf_beta                = float, False
    vdw_corr                  = str,   False, None, ('none', 'grimme-d2', 'grimme-d3', 'tkatchenko-scheffler', 'many-body-dispersion', 'XDM', 'Grimme-D2', 'DFT-D', 'dft-d', 'Grimme-D3', 'DFT-D3', 'dft-d3', 'TS', 'ts', 'ts-vdw', 'ts-vdW', 'MBD', 'mbd', 'mbd_vdw', 'xdm', 'many-body dispersion')
    london                    = bool,  False
    london_s6                 = float, False
    london_rcut               = float, False
    dftd3_version             = int,   False
    dftd3_threebody           = bool,  False
    ts_vdw_econv_thr          = float, False
    ts_vdw_isolated           = bool,  False
    xdm                       = bool,  False
    xdm_a1                    = float, False
    xdm_a2                    = float, False
    space_group               = int,   False
    uniqueb                   = bool,  False
    origin_choice             = int,   False
    rhombohedral              = bool,  False
    nextffield                = int,   False, None, None, '7.2.0'
    celldm                    = float, False, (1, 6)
    A                         = float, False
    B                         = float, False
    C                         = float, False
    cosAB                     = float, False
    cosAC                     = float, False
    cosBC                     = float, False
    zgate                     = float, False
    relaxz                    = bool,  False
    block                     = bool,  False
    block_1                   = float, False
    block_2                   = float, False
    block_height              = float, False
    starting_charge           = float, False, (1, 'ntyp')
    starting_magnetization    = float, False, (1, 'ntyp')
    Hubbard_beta              = float, False, (1, 'ntyp')
    angle1                    = float, False, (1, 'ntyp')
    angle2                    = float, False, (1, 'ntyp')
    fixed_magnetization       = float, False, (1, 3)
    london_c6                 = float, False, (1, 'ntyp')
    london_rvdw               = float, False, (1, 'ntyp')
    nr1                       = int,   False
    nr2                       = int,   False
    nr3                       = int,   False
    nr1s                      = int,   False
    nr2s                      = int,   False
    nr3s                      = int,   False
    nqx1                      = int,   False
    nqx2                      = int,   False
    nqx3                      = int,   False
    Hubbard_occ               = float, False, ((1, 1), ('ntyp', 3)), None, '7.1.0'
    starting_ns_eigenvalue    = float, False, ((1, 1, 1), ('2*lmax+1', 'nspin or npol', 'ntyp'))
    Hubbard_alpha             = float, False, (1, 'ntyp'), None, None, '7.5.0'
    lda_plus_u                = bool,  False, None, None, None, '7.1.0'
    lda_plus_u_kind           = int,   False, None, None, None, '7.1.0'
    U_projection_type         = str,   False, None, ('atomic', 'ortho-atomic', 'norm-atomic', 'file', 'pseudo'), None, '7.1.0'
    Hubbard_parameters        = str,   False, None, ('input', 'file'), None, '7.1.0'
    Hubbard_U                 = float, False, (1, 'ntyp'), None, None, '7.1.0'
    Hubbard_J0                = float, False, (1, 'ntype'), None, None, '7.1.0'
    Hubbard_V                 = float, False, ((1, 1, 1), ('natx', '27*natx', 4)), None, None, '7.1.0'
    Hubbard_J                 = float, False, ((1, 1), (3, 'ntyp')), None, None, '7.1.0'
    #          name           = type, required, shape, allowed_values, v_added, v_removed
#end class SystemDefinitions


class ElectronsDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &ELECTRONS input namelist for ``pw.x``."""

    #       name       = type, required, shape, allowed_values, v_added, v_removed
    electron_maxstep   = int,   False
    exx_maxstep        = int,   False, None, None, '7.2.0'
    scf_must_converge  = bool,  False
    conv_thr           = float, False
    adaptive_thr       = bool,  False
    conv_thr_init      = float, False
    conv_thr_multi     = float, False
    mixing_mode        = str,   False, None, ('plain', 'TF', 'local-TF')
    mixing_beta        = float, False
    mixing_ndim        = int,   False
    mixing_fixed_ns    = int,   False
    diagonalization    = str,   False, None, ('david', 'cg', 'ppcg', 'paro', 'rmm-davidson', 'rmm-paro', 'direct', 'ParO')
    diago_thr_init     = float, False
    diago_cg_maxiter   = int,   False
    diago_david_ndim   = int,   False
    diago_rmm_ndim     = int,   False
    diago_rmm_conv     = bool,  False
    diago_gs_nblock    = int,   False, None, None, '7.1.0'
    diago_full_acc     = bool,  False
    efield             = float, False
    efield_phase       = str,   False, None, ('read', 'write', 'none')
    startingpot        = str,   False, None, ('atomic', 'file')
    startingwfc        = str,   False, None, ('atomic', 'atomic+random', 'random', 'file')
    tqr                = bool,  False
    real_space         = bool,  False
    efield_cart        = float, False, (1, 3)
    diago_ppcg_maxiter = int,   False, None, None, '7.1.0', '7.5.0'
    #       name       = type, required, shape, allowed_values, v_added, v_removed
#end class ElectronsDefinitions


class IonsDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &IONS input namelist for ``pw.x``."""

    #      name       = type, required, shape, allowed_values, v_added, v_removed
    ion_positions     = str,   False, None, ('default', 'from_input')
    ion_velocities    = str,   False, None, ('default', 'from_input')
    ion_dynamics      = str,   False, None, ('none', 'bfgs', 'damp', 'fire', 'verlet', 'velocity-verlet', 'langevin', 'langevin-smc', 'beeman')
    pot_extrapolation = str,   False, None, ('none', 'atomic', 'first_order', 'second_order')
    wfc_extrapolation = str,   False, None, ('none', 'first_order', 'second_order')
    remove_rigid_rot  = bool,  False
    ion_temperature   = str,   False, None, ('rescaling', 'rescale-v', 'rescale-T', 'reduce-T', 'nose', 'berendsen', 'andersen', 'svr', 'initial', 'not_controlled')
    tempw             = float, False
    fnosep            = float, False, None, None, '7.5.0'
    nhpcl             = int,   False, None, None, '7.5.0'
    nhptyp            = int,   False, None, None, '7.5.0'
    ndega             = int,   False, None, None, '7.5.0'
    tolp              = float, False
    delta_t           = float, False
    nraise            = int,   False
    refold_pos        = bool,  False
    nhgrp             = int,   False, (1, 'ntyp'), None, '7.5.0'
    fnhscl            = float, False, (1, 'ntyp'), None, '7.5.0'
    upscale           = float, False
    bfgs_ndim         = int,   False
    tgdiis_step       = bool,  False, None, None, '7.5.0'
    trust_radius_max  = float, False
    trust_radius_min  = float, False
    trust_radius_ini  = float, False
    w_1               = float, False
    w_2               = float, False
    fire_alpha_init   = float, False
    fire_falpha       = float, False
    fire_nmin         = int,   False
    fire_f_inc        = float, False
    fire_f_dec        = float, False
    fire_dtmax        = float, False
    #      name       = type, required, shape, allowed_values, v_added, v_removed
#end class IonsDefinitions


class CellDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &CELL input namelist for ``pw.x``."""

    #     name     = type, required, shape, allowed_values, v_added, v_removed
    cell_dynamics  = str,   False, None, ('none', 'sd', 'damp-pr', 'damp-w', 'bfgs', 'pr', 'w')
    press          = float, False
    wmass          = float, False
    cell_factor    = float, False
    press_conv_thr = float, False
    cell_dofree    = str,   False, None, ('all', 'ibrav', 'a', 'b', 'c', 'fixa', 'fixb', 'fixc', 'x', 'y', 'z', 'xy', 'xz', 'yz', 'xyz', 'shape', 'volume', '2Dxy', '2Dshape', 'epitaxial_ab', 'epitaxial_ac', 'epitaxial_bc')
    #     name     = type, required, shape, allowed_values, v_added, v_removed
#end class CellDefinitions


class FcpDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &FCP input namelist for ``pw.x``."""

    #      name      = type, required, shape, allowed_values, v_added, v_removed
    fcp_mu           = float, True
    fcp_dynamics     = str,   False, None, ('none', 'bfgs', 'newton', 'damp', 'lm', 'velocity-verlet', 'verlet')
    fcp_conv_thr     = float, False
    fcp_ndiis        = int,   False
    freeze_all_atoms = bool,  False
    fcp_mass         = float, False
    fcp_velocity     = float, False
    fcp_temperature  = str,   False, None, ('rescaling', 'rescale-v', 'rescale-T', 'reduce-T', 'berendsen', 'andersen', 'initial', 'not_controlled')
    fcp_tempw        = float, False
    fcp_tolp         = float, False
    fcp_delta_t      = float, False
    fcp_nraise       = int,   False
    #      name      = type, required, shape, allowed_values, v_added, v_removed
#end class FcpDefinitions


class RismDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &RISM input namelist for ``pw.x``."""

    #        name         = type, required, shape, allowed_values, v_added, v_removed
    nsolv                 = int,   True,  None, None, '7.1.0'
    closure               = str,   False, None, ('kh', 'hnc'), '7.1.0'
    tempv                 = float, False, None, None, '7.1.0'
    ecutsolv              = float, False, None, None, '7.1.0'
    starting1d            = str,   False, None, ('zero', 'file', 'fix'), '7.1.0'
    starting3d            = str,   False, None, ('zero', 'file'), '7.1.0'
    smear1d               = float, False, None, None, '7.1.0'
    smear3d               = float, False, None, None, '7.1.0'
    rism1d_maxstep        = int,   False, None, None, '7.1.0'
    rism3d_maxstep        = int,   False, None, None, '7.1.0'
    rism1d_conv_thr       = float, False, None, None, '7.1.0'
    rism3d_conv_thr       = float, False, None, None, '7.1.0'
    mdiis1d_size          = int,   False, None, None, '7.1.0'
    mdiis3d_size          = int,   False, None, None, '7.1.0'
    mdiis1d_step          = float, False, None, None, '7.1.0'
    mdiis3d_step          = float, False, None, None, '7.1.0'
    rism1d_bond_width     = float, False, None, None, '7.1.0'
    rism1d_dielectric     = float, False, None, None, '7.1.0'
    rism1d_molesize       = float, False, None, None, '7.1.0'
    rism1d_nproc          = int,   False, None, None, '7.1.0'
    rism3d_conv_level     = float, False, None, None, '7.1.0'
    rism3d_planar_average = bool,  False, None, None, '7.1.0'
    laue_nfit             = int,   False, None, None, '7.1.0'
    laue_expand_right     = float, False, None, None, '7.1.0'
    laue_expand_left      = float, False, None, None, '7.1.0'
    laue_starting_right   = float, False, None, None, '7.1.0'
    laue_starting_left    = float, False, None, None, '7.1.0'
    laue_buffer_right     = float, False, None, None, '7.1.0'
    laue_buffer_left      = float, False, None, None, '7.1.0'
    laue_both_hands       = bool,  False, None, None, '7.1.0'
    laue_wall             = str,   False, None, ('none', 'auto', 'manual'), '7.1.0'
    laue_wall_z           = float, False, None, None, '7.1.0'
    laue_wall_rho         = float, False, None, None, '7.1.0'
    laue_wall_epsilon     = float, False, None, None, '7.1.0'
    laue_wall_sigma       = float, False, None, None, '7.1.0'
    laue_wall_lj6         = bool,  False, None, None, '7.1.0'
    solute_lj             = str,   False, (1, 'ntyp'), None, '7.1.0'
    solute_epsilon        = float, False, (1, 'ntyp'), None, '7.1.0'
    solute_sigma          = float, False, (1, 'ntyp'), None, '7.1.0'
    #        name         = type, required, shape, allowed_values, v_added, v_removed
#end class RismDefinitions
