"""Module for storing input parameters for Quantum ESPRESSO.

The code in this module was auto-generated by a Python script that
uses the intermediate XML representation of QE's ``pw.x`` input
description files.

The script is at ``qmcpack/nexus/dev_utils/gen_pwscf_input_data.py``.

A description of how to turn QE's ``.def`` documentation files into
XML is given in QE's repository, at ``q-e/dev-tools/README.helpdoc``.

This module's code was autogenerated on Wed 15 Jul 2026, 08:35PM

The supported QE versions are v4.0.4-v7.6.0
"""

from __future__ import annotations
from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

PwscfInputType: TypeAlias = str | bool | int | float | Sequence
# For structured array inputs (k-points, weights, reciprocal lattice, etc.)
PwscfArrayInput: TypeAlias = Sequence[float | Sequence[float]]


@dataclass(frozen=True) # We generally don't want any of these to be modified
class NamelistParamDefinition:
    """Base class for all namelist variables."""

    datatype:        tuple[PwscfInputType]
    required:        bool
    shape:           tuple | None = None
    allowed_values:  tuple[PwscfInputType] | None = None
    dependencies:    tuple[NamelistParamDefinition] | None = None
    version_added:   tuple[float] | None = None
    version_removed: tuple[float] | None = None
#end class NamelistDefinition


class NamelistEnumBase(Enum):
    """Abstract base class for the namelist enumerations.

    Provides the ``__new__`` method for the enums.
    """
    def __new__(
        cls,
        datatype:        PwscfInputType,
        required:        bool,
        allowed_values:  tuple[PwscfInputType] | None = None,
        dependencies:    tuple[NamelistParamDefinition] | None = None,
        version_added:   tuple[float] | None = None,
        version_removed: tuple[float] | None = None,
    ):
        definition = NamelistParamDefinition.__new__(cls)
        definition._value_ = NamelistParamDefinition(
            datatype,
            required,
            allowed_values,
            dependencies,
            version_added,
            version_removed,
        )
        return definition
#end class NamelistEnumBase


class ControlDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &CONTROL input namelist for ``pw.x``."""

    calculation   = str,   False, None, ('scf', 'nscf', 'bands', 'relax', 'md', 'vc-relax', 'vc-md')
    title         = str,   0      
    verbosity     = str,   False, None, ('high', 'low')
    restart_mode  = str,   False, None, ('from_scratch', 'restart')
    wf_collect    = bool,  0      
    nstep         = int,   0      
    iprint        = int,   0      
    tstress       = bool,  0      
    tprnfor       = bool,  0      
    dt            = float, 0      
    outdir        = str,   0      
    wfcdir        = str,   0      
    prefix        = str,   0      
    lkpoint_dir   = bool,  0      
    max_seconds   = float, 0      
    etot_conv_thr = float, 0      
    forc_conv_thr = float, 0      
    disk_io       = str,   False, None, ('default', 'high', 'medium', 'low', 'nowf', 'minimal', 'none')
    pseudo_dir    = str,   0      
    tefield       = bool,  0      
    dipfield      = bool,  0      
    lelfield      = bool,  0      
    nberrycyc     = int,   0      
    lorbm         = bool,  0      
    lberry        = bool,  0      
    gdir          = int,   0      
    nppstr        = int,   0      
    gate          = bool,  0      
    twochem       = bool,  0      
    lfcp          = bool,  0      
    trism         = bool,  0      
#end class ControlDefinitions


class SystemDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &SYSTEM input namelist for ``pw.x``."""

    ibrav                     = int,   1      
    nat                       = int,   1      
    ntyp                      = int,   1      
    nbnd                      = int,   0      
    nbnd_cond                 = int,   0      
    tot_charge                = float, 0      
    tot_magnetization         = float, 0      
    ecutwfc                   = float, 1      
    ecutrho                   = float, 0      
    ecutfock                  = float, 0      
    nosym                     = bool,  0      
    nosym_evc                 = bool,  0      
    noinv                     = bool,  0      
    no_t_rev                  = bool,  0      
    force_symmorphic          = bool,  0      
    use_all_frac              = bool,  0      
    occupations               = str,   False, None, ('smearing', 'tetrahedra', 'tetrahedra_lin', 'tetrahedra_opt', 'fixed', 'from_input')
    one_atom_occupations      = bool,  0      
    starting_spin_angle       = bool,  0      
    degauss_cond              = float, 0      
    nelec_cond                = float, 0      
    degauss                   = float, 0      
    smearing                  = str,   False, None, ('gaussian', 'methfessel-paxton', 'marzari-vanderbilt', 'fermi-dirac')
    nspin                     = int,   0      
    sic_gamma                 = float, 0      
    pol_type                  = str,   False, None, ('none', 'e', 'h')
    sic_energy                = bool,  0      
    sci_vb                    = float, 0      
    sci_cb                    = float, 0      
    noncolin                  = bool,  0      
    ecfixed                   = float, 0      
    qcutz                     = float, 0      
    q2sigma                   = float, 0      
    input_dft                 = str,   0      
    ace                       = bool,  0      
    exx_fraction              = float, 0      
    screening_parameter       = float, 0      
    exxdiv_treatment          = str,   False, None, ('gygi-baldereschi', 'vcut_spherical', 'vcut_ws', 'none')
    exx_type                  = str,   False, None, ('bands', 'band_pairs')
    x_gamma_extrapolation     = bool,  0      
    ecutvcut                  = float, 0      
    localization_thr          = float, 0      
    dmft                      = bool,  0      
    dmft_prefix               = str,   0      
    ensemble_energies         = bool,  0      
    edir                      = int,   0      
    emaxpos                   = float, 0      
    eopreg                    = float, 0      
    eamp                      = float, 0      
    lforcet                   = bool,  0      
    constrained_magnetization = str,   False, None, ('none', 'total', 'atomic', 'total direction', 'atomic direction')
    lambda_                   = float, 0      
    report                    = int,   0      
    lspinorb                  = bool,  0      
    assume_isolated           = str,   False, None, ('none', 'makov-payne', 'martyna-tuckerman', 'esm', '2D')
    esm_bc                    = str,   False, None, ('pbc', 'bc1', 'bc2', 'bc3')
    esm_w                     = float, 0      
    esm_efield                = float, 0      
    esm_nfit                  = int,   0      
    lgcscf                    = bool,  0      
    gcscf_mu                  = float, 0      
    gcscf_conv_thr            = float, 0      
    gcscf_beta                = float, 0      
    vdw_corr                  = str,   False, None, ('none', 'grimme-d2', 'grimme-d3', 'tkatchenko-scheffler', 'many-body-dispersion', 'XDM')
    london                    = bool,  0      
    london_s6                 = float, 0      
    london_rcut               = float, 0      
    dftd3_version             = int,   0      
    dftd3_threebody           = bool,  0      
    ts_vdw_econv_thr          = float, 0      
    ts_vdw_isolated           = bool,  0      
    xdm                       = bool,  0      
    xdm_a1                    = float, 0      
    xdm_a2                    = float, 0      
    space_group               = int,   0      
    uniqueb                   = bool,  0      
    origin_choice             = int,   0      
    rhombohedral              = bool,  0      
    nextffield                = int,   0      
    celldm                    = float, False, ((1,), (6,))
    A                         = float, 0      
    B                         = float, 0      
    C                         = float, 0      
    cosAB                     = float, 0      
    cosAC                     = float, 0      
    cosBC                     = float, 0      
    zgate                     = float, 0      
    relaxz                    = bool,  0      
    block                     = bool,  0      
    block_1                   = float, 0      
    block_2                   = float, 0      
    block_height              = float, 0      
    starting_charge           = float, False, ((1,), ('ntyp',))
    starting_magnetization    = float, False, ((1,), ('ntyp',))
    Hubbard_beta              = float, False, ((1,), ('ntyp',))
    angle1                    = float, False, ((1,), ('ntyp',))
    angle2                    = float, False, ((1,), ('ntyp',))
    fixed_magnetization       = float, False, ((1,), (3,))
    london_c6                 = float, False, ((1,), ('ntyp',))
    london_rvdw               = float, False, ((1,), ('ntyp',))
    nr1                       = int,   0      
    nr2                       = int,   0      
    nr3                       = int,   0      
    nr1s                      = int,   0      
    nr2s                      = int,   0      
    nr3s                      = int,   0      
    nqx1                      = int,   0      
    nqx2                      = int,   0      
    nqx3                      = int,   0      
    Hubbard_occ               = float, False, ((1,), ('ntyp,3',))
    starting_ns_eigenvalue    = float, False, ((1,), ('2*lmax+1,nspin or npol,ntyp',))
#end class SystemDefinitions


class ElectronsDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &ELECTRONS input namelist for ``pw.x``."""

    electron_maxstep  = int,   0      
    exx_maxstep       = int,   0      
    scf_must_converge = bool,  0      
    conv_thr          = float, 0      
    adaptive_thr      = bool,  0      
    conv_thr_init     = float, 0      
    conv_thr_multi    = float, 0      
    mixing_mode       = str,   False, None, ('plain', 'TF', 'local-TF')
    mixing_beta       = float, 0      
    mixing_ndim       = int,   0      
    mixing_fixed_ns   = int,   0      
    diagonalization   = str,   False, None, ('david', 'cg', 'ppcg', 'paro', 'rmm-davidson', 'rmm-paro', 'direct')
    diago_thr_init    = float, 0      
    diago_cg_maxiter  = int,   0      
    diago_david_ndim  = int,   0      
    diago_rmm_ndim    = int,   0      
    diago_rmm_conv    = bool,  0      
    diago_gs_nblock   = int,   0      
    diago_full_acc    = bool,  0      
    efield            = float, 0      
    efield_phase      = str,   False, None, ('read', 'write', 'none')
    startingpot       = str,   False, None, ('atomic', 'file')
    startingwfc       = str,   False, None, ('atomic', 'atomic+random', 'random', 'file')
    tqr               = bool,  0      
    real_space        = bool,  0      
    efield_cart       = float, False, ((1,), (3,))
#end class ElectronsDefinitions


class IonsDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &IONS input namelist for ``pw.x``."""

    ion_positions     = str,   False, None, ('default', 'from_input')
    ion_velocities    = str,   False, None, ('default', 'from_input')
    ion_dynamics      = str,   False, None, ('none', 'bfgs', 'damp', 'fire', 'verlet', 'velocity-verlet', 'langevin', 'langevin-smc', 'bfgs', 'damp', 'beeman')
    pot_extrapolation = str,   False, None, ('none', 'atomic', 'first_order', 'second_order')
    wfc_extrapolation = str,   False, None, ('none', 'first_order', 'second_order')
    remove_rigid_rot  = bool,  0      
    ion_temperature   = str,   False, None, ('rescaling', 'rescale-v', 'rescale-T', 'reduce-T', 'nose', 'berendsen', 'andersen', 'svr', 'initial', 'not_controlled')
    tempw             = float, 0      
    fnosep            = float, 0      
    nhpcl             = int,   0      
    nhptyp            = int,   0      
    ndega             = int,   0      
    tolp              = float, 0      
    delta_t           = float, 0      
    nraise            = int,   0      
    refold_pos        = bool,  0      
    nhgrp             = int,   False, ((1,), ('ntyp',))
    fnhscl            = float, False, ((1,), ('ntyp',))
    upscale           = float, 0      
    bfgs_ndim         = int,   0      
    tgdiis_step       = bool,  0      
    trust_radius_max  = float, 0      
    trust_radius_min  = float, 0      
    trust_radius_ini  = float, 0      
    w_1               = float, 0      
    w_2               = float, 0      
    fire_alpha_init   = float, 0      
    fire_falpha       = float, 0      
    fire_nmin         = int,   0      
    fire_f_inc        = float, 0      
    fire_f_dec        = float, 0      
    fire_dtmax        = float, 0      
#end class IonsDefinitions


class CellDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &CELL input namelist for ``pw.x``."""

    cell_dynamics  = str,   False, None, ('none', 'sd', 'damp-pr', 'damp-w', 'bfgs', 'none', 'pr', 'w')
    press          = float, 0      
    wmass          = float, 0      
    cell_factor    = float, 0      
    press_conv_thr = float, 0      
    cell_dofree    = str,   False, None, ('all', 'ibrav', 'a', 'b', 'c', 'fixa', 'fixb', 'fixc', 'x', 'y', 'z', 'xy', 'xz', 'yz', 'xyz', 'shape', 'volume', '2Dxy', '2Dshape', 'epitaxial_ab', 'epitaxial_ac', 'epitaxial_bc')
#end class CellDefinitions


class FcpDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &FCP input namelist for ``pw.x``."""

    fcp_mu           = float, 1      
    fcp_dynamics     = str,   False, None, ('none', 'bfgs', 'newton', 'damp', 'lm', 'velocity-verlet', 'verlet')
    fcp_conv_thr     = float, 0      
    fcp_ndiis        = int,   0      
    freeze_all_atoms = bool,  0      
    fcp_mass         = float, 0      
    fcp_velocity     = float, 0      
    fcp_temperature  = str,   False, None, ('rescaling', 'rescale-v', 'rescale-T', 'reduce-T', 'berendsen', 'andersen', 'initial', 'not_controlled')
    fcp_tempw        = float, 0      
    fcp_tolp         = float, 0      
    fcp_delta_t      = float, 0      
    fcp_nraise       = int,   0      
#end class FcpDefinitions


class RismDefinitions(NamelistParamDefinition, NamelistEnumBase):
    """All variables belonging to the &RISM input namelist for ``pw.x``."""

    nsolv                 = int,   1      
    closure               = str,   False, None, ('kh', 'hnc')
    tempv                 = float, 0      
    ecutsolv              = float, 0      
    starting1d            = str,   False, None, ('zero', 'file', 'fix')
    starting3d            = str,   False, None, ('zero', 'file')
    smear1d               = float, 0      
    smear3d               = float, 0      
    rism1d_maxstep        = int,   0      
    rism3d_maxstep        = int,   0      
    rism1d_conv_thr       = float, 0      
    rism3d_conv_thr       = float, 0      
    mdiis1d_size          = int,   0      
    mdiis3d_size          = int,   0      
    mdiis1d_step          = float, 0      
    mdiis3d_step          = float, 0      
    rism1d_bond_width     = float, 0      
    rism1d_dielectric     = float, 0      
    rism1d_molesize       = float, 0      
    rism1d_nproc          = int,   0      
    rism3d_conv_level     = float, 0      
    rism3d_planar_average = bool,  0      
    laue_nfit             = int,   0      
    laue_expand_right     = float, 0      
    laue_expand_left      = float, 0      
    laue_starting_right   = float, 0      
    laue_starting_left    = float, 0      
    laue_buffer_right     = float, 0      
    laue_buffer_left      = float, 0      
    laue_both_hands       = bool,  0      
    laue_wall             = str,   False, None, ('none', 'auto', 'manual')
    laue_wall_z           = float, 0      
    laue_wall_rho         = float, 0      
    laue_wall_epsilon     = float, 0      
    laue_wall_sigma       = float, 0      
    laue_wall_lj6         = bool,  0      
    solute_lj             = str,   False, ((1,), ('ntyp',))
    solute_epsilon        = float, False, ((1,), ('ntyp',))
    solute_sigma          = float, False, ((1,), ('ntyp',))
#end class RismDefinitions
