# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(developer-heg_54_J2rpa-16-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "16" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "heg.rpa.rs5.xml")
set_tests_properties(developer-heg_54_J2rpa-16-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "bug;hard_fail;quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/developer-heg_54_J2rpa-16-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;14;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(developer-heg_54_J2rpa-16-1-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "1" "-p" "HEG.rs5.rpa" "-e" "2" "--le" "-4.209725  0.02")
set_tests_properties(developer-heg_54_J2rpa-16-1-totenergy PROPERTIES  DEPENDS "developer-heg_54_J2rpa-16-1" LABELS "QMCPACK-checking-results;unstable;bug;hard_fail;quality_unknown" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/developer-heg_54_J2rpa-16-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;14;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(deterministic-heg_54_J2rpa-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "det_heg.rpa.rs5.xml")
set_tests_properties(deterministic-heg_54_J2rpa-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;deterministic;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/deterministic-heg_54_J2rpa-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;37;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(deterministic-heg_54_J2rpa-1-1-kinetic "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "1" "-p" "det_HEG.rs5.rpa" "-e" "2" "--ke" "3.27072556 0.000001")
set_tests_properties(deterministic-heg_54_J2rpa-1-1-kinetic PROPERTIES  DEPENDS "deterministic-heg_54_J2rpa-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/deterministic-heg_54_J2rpa-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;37;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(deterministic-heg_54_J2rpa-1-1-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "1" "-p" "det_HEG.rs5.rpa" "-e" "2" "--le" "-3.91514075 0.000001")
set_tests_properties(deterministic-heg_54_J2rpa-1-1-totenergy PROPERTIES  DEPENDS "deterministic-heg_54_J2rpa-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/deterministic-heg_54_J2rpa-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;37;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(deterministic-heg_54_J2rpa-1-1-eeenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "1" "-p" "det_HEG.rs5.rpa" "-e" "2" "--ee" "-7.18586631 0.000001")
set_tests_properties(deterministic-heg_54_J2rpa-1-1-eeenergy PROPERTIES  DEPENDS "deterministic-heg_54_J2rpa-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/deterministic-heg_54_J2rpa-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;37;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
add_test(deterministic-heg_54_J2rpa-1-1-potential "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "1" "-p" "det_HEG.rs5.rpa" "-e" "2" "--lp" "-7.18586631 0.000001")
set_tests_properties(deterministic-heg_54_J2rpa-1-1-potential PROPERTIES  DEPENDS "deterministic-heg_54_J2rpa-1-1" LABELS "QMCPACK-checking-results;quality_unknown;deterministic" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/heg/heg_54_J2rpa/deterministic-heg_54_J2rpa-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;37;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/heg/heg_54_J2rpa/CMakeLists.txt;0;")
