#!/bin/bash
#
#PBS -A mat151
#PBS -N QMCPACKTestTitan
#PBS -j oe
#PBS -l walltime=2:00:00,nodes=1
#PBS -q batch
#PBS -m e
#PBS -M kentpr@ornl.gov

#
# Setup for titan.ccs.ornl.gov
#
# Run the "short" nightlies, requeue if an executable is built.
#
# Titan I/O and compile is incredibly slow -> generous build/test times
# 
# Location of job script must be set at end ($HOME/.qmcpack_test_jobs/... ) for resubmit
#
# Checkout, build, and run on scratch. Use custom names for checkout
# directory because scratch is shared.
#

cd $PBS_O_WORKDIR

# Directory in which to run tests. Should be an absolute path and fastest usable filesystem
test_path=$MEMBERWORK/mat151
# Name of machine on which run. Used to set build directory names.
machine_name=titan

test_dir=${test_path}/QMCPACK_CI_BUILDS_DO_NOT_REMOVE

if [ -e ${test_path} ]; then

if [ ! -e ${test_dir} ]; then
mkdir ${test_dir}
fi

if [ -e ${test_dir} ]; then
cd ${test_dir}

# Minimize load on GitHub by maintaining a local cloned git used for all builds
if [ ! -e qmcpack ]; then
echo --- Cloning QMCPACK git `date`
git clone https://github.com/QMCPACK/qmcpack.git --depth 1
else
cd qmcpack
echo --- Updating local QMCPACK git `date`
git pull
cd ..
fi

# Sanity check cmake config file present
if [ -e qmcpack/CMakeLists.txt ]; then

echo --- Starting test builds and tests

for sys in build_gnu_cuda
do

cd ${test_dir}

# Prepend directories with machine name so the same workspace can be used with other machines
if [ -e ${machine_name}_$sys ]; then
rm -r -f ${machine_name}_$sys
fi
mkdir ${machine_name}_$sys
cd ${machine_name}_$sys

case $sys in
"build_gnu")
# Build with GNU PrgEnv on titan, not default PGI.

    current_prgenv=`echo $LOADEDMODULES|sed -e 's/.*PrgEnv/PrgEnv/' -e 's/\/.*//g'`
    echo $current_prgenv
    module swap $current_prgenv PrgEnv-gnu
    if (echo $LOADEDMODULES | grep -q cudatoolkit)
    then
    echo "Unloading cudatoolkit for CPU code compilation."
    module unload cudatoolkit
    fi

    module load cray-hdf5
    module load cmake/2.8.11.2
    module load fftw
    export FFTW_HOME=$FFTW_DIR/..
    module load boost
    export QMCPACK_TEST_SUBMIT_NAME=GCC-Release
    ctest -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=CC -S $PWD/../qmcpack/CMake/ctest_script.cmake,release -R 'short|converter|unit' -E 'diamond' -VV --timeout 7200
    ;;
"build_gnu_complex")

# Build with GNU PrgEnv on titan, not default PGI

    current_prgenv=`echo $LOADEDMODULES|sed -e 's/.*PrgEnv/PrgEnv/' -e 's/\/.*//g'`
    echo $current_prgenv
    module swap $current_prgenv PrgEnv-gnu
    if (echo $LOADEDMODULES | grep -q cudatoolkit)
    then
    echo "Unloading cudatoolkit for CPU code compilation."
    module unload cudatoolkit
    fi

    module load cray-hdf5
    module load cmake/2.8.11.2
    module load fftw
    export FFTW_HOME=$FFTW_DIR/..
    module load boost
    export QMCPACK_TEST_SUBMIT_NAME=GCC-Complex-Release
    ctest -DQMC_COMPLEX=1 -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=CC -S $PWD/../qmcpack/CMake/ctest_script.cmake,release -R 'short|converter|unit' -E 'diamond' -VV --timeout 7200
    ;;
"build_gnu_cuda")
# Build with GNU PrgEnv on titan, not default PGI.
    current_prgenv=`echo $LOADEDMODULES|sed -e 's/.*PrgEnv/PrgEnv/' -e 's/\/.*//g'`
    echo $current_prgenv
    module swap $current_prgenv PrgEnv-gnu

    module load cudatoolkit
    module load cray-hdf5
    module load cmake/2.8.11.2
    module load fftw
    export FFTW_HOME=$FFTW_DIR/..
    module load boost
    export QMCPACK_TEST_SUBMIT_NAME=GCC-CUDA-Release
    ctest -DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=CC -DQMC_CUDA=1 -S $PWD/../qmcpack/CMake/ctest_script.cmake,release -R 'short|converter|unit' -E 'diamond' -VV --timeout 7200
    ;;
*)
    echo "ERROR: Unknown build type $sys"
    ;;
esac

done

else
echo "ERROR: No CMakeLists. Bad git clone or update"
exit 1
fi

else
echo "ERROR: Unable to make test directory ${test_dir}"
exit 1
fi

else
echo "ERROR: No directory ${test_path}"
exit 1
fi

# Hard-coded logic for resubmission
# Default gnu build executable must be present

if [ -e ${test_dir}/${machine_name}_build_gnu/bin/qmcpack ]; then
echo "--- Found a built qmcpack executable. Will requeue."
cd $HOME/.qmcpack_test_jobs
if [ -e nightly_ornl_olcf_titan_gpu.job ]; then
# Run after 11.21pm following Tuesday. This is usually the evening after maintenance
echo -- Qsub
qsub -a `date -d "next Tuesday" +%m%d2321` nightly_ornl_olcf_titan_gpu.job
# Run after 11.01pm next day
#qsub -a 2301 $HOME/.qmcpack_test_jobs/nightly_ornl_olcf_titan_cpu.job
# Run after one week
#qsub -a `date -d "+1 week" +%m%d%H%M` $HOME/.qmcpack_test_jobs/nightly_ornl_olcf_titan_cpu.job
# Example for debugging:
#qsub -a `date -d "+1 hour" +%m%d%H%M` $HOME/.qmcpack_test_jobs/nightly_ornl_olcf_titan_cpu.job
fi
else
echo "ERROR: No built qmcpack executable. Will NOT requeue."
fi
