# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(short-sho-vmc-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "vmc_sho.xml")
set_tests_properties(short-sho-vmc-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;21;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-vmc-1-16-kinetic "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "m5" "-e" "2" "--ke" "0.225 0.0028")
set_tests_properties(short-sho-vmc-1-16-kinetic PROPERTIES  DEPENDS "short-sho-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;21;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-vmc-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "m5" "-e" "2" "--le" "0.45  4.0e-14")
set_tests_properties(short-sho-vmc-1-16-totenergy PROPERTIES  DEPENDS "short-sho-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;21;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-vmc-1-16-potential "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "m5" "-e" "2" "--lp" "0.225 0.0028")
set_tests_properties(short-sho-vmc-1-16-potential PROPERTIES  DEPENDS "short-sho-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;21;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-vmc-1-16-latdev "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "m5" "-e" "2" "--latdev" "1.0   0.013")
set_tests_properties(short-sho-vmc-1-16-latdev PROPERTIES  DEPENDS "short-sho-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;21;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-grad_lap-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "grad_lap.xml")
set_tests_properties(short-sho-grad_lap-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-grad_lap-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;583;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;33;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-sho-grad_lap-1-1-check "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_grad_lap.py")
set_tests_properties(short-sho-grad_lap-1-1-check PROPERTIES  DEPENDS "short-sho-grad_lap-1-1" LABELS "quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-sho-grad_lap-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;610;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;33;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-grid_ext_pot-vmc-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "vmc_grid_ext_pot.xml")
set_tests_properties(short-grid_ext_pot-vmc-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-grid_ext_pot-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;35;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-grid_ext_pot-vmc-1-16-kinetic "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "grid_ext_pot" "-e" "2" "--ke" "0.225 0.0028")
set_tests_properties(short-grid_ext_pot-vmc-1-16-kinetic PROPERTIES  DEPENDS "short-grid_ext_pot-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-grid_ext_pot-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;35;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-grid_ext_pot-vmc-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "grid_ext_pot" "-e" "2" "--le" "0.45  1e-6")
set_tests_properties(short-grid_ext_pot-vmc-1-16-totenergy PROPERTIES  DEPENDS "short-grid_ext_pot-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-grid_ext_pot-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;35;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-grid_ext_pot-vmc-1-16-potential "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "grid_ext_pot" "-e" "2" "--lp" "0.225 0.0028")
set_tests_properties(short-grid_ext_pot-vmc-1-16-potential PROPERTIES  DEPENDS "short-grid_ext_pot-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-grid_ext_pot-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;35;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
add_test(short-grid_ext_pot-vmc-1-16-latdev "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "grid_ext_pot" "-e" "2" "--latdev" "1.0   0.013")
set_tests_properties(short-grid_ext_pot-vmc-1-16-latdev PROPERTIES  DEPENDS "short-grid_ext_pot-vmc-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/models/short-grid_ext_pot-vmc-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;35;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/models/CMakeLists.txt;0;")
