# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(short-monoO_1x1x1_pp-vmc_sdj-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "qmc_short.in.xml")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;5;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(short-monoO_1x1x1_pp-vmc_sdj-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_short" "-e" "2" "--le" "-31.776596 0.006")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj-1-16-totenergy PROPERTIES  DEPENDS "short-monoO_1x1x1_pp-vmc_sdj-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;5;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(short-monoO_1x1x1_pp-vmc_sdj-1-16-samples "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_short" "-e" "2" "--ts" "64000 0.0")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj-1-16-samples PROPERTIES  DEPENDS "short-monoO_1x1x1_pp-vmc_sdj-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;5;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(short-monoO_1x1x1_pp-vmc_sdj3-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "qmc_j3_short.in.xml")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj3-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;19;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(short-monoO_1x1x1_pp-vmc_sdj3-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_j3_short" "-e" "2" "--le" "-31.913838 0.0025")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj3-1-16-totenergy PROPERTIES  DEPENDS "short-monoO_1x1x1_pp-vmc_sdj3-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;19;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(short-monoO_1x1x1_pp-vmc_sdj3-1-16-samples "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_j3_short" "-e" "2" "--ts" "204800 0.0")
set_tests_properties(short-monoO_1x1x1_pp-vmc_sdj3-1-16-samples PROPERTIES  DEPENDS "short-monoO_1x1x1_pp-vmc_sdj3-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/short-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;19;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "qmc_long.in.xml")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;39;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_long" "-e" "2" "--le" "-31.776596 0.0002")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj-1-16-totenergy PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;39;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj-1-16-samples "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_long" "-e" "2" "--ts" "61440000 0.0")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj-1-16-samples PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;39;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj-1-16-flux "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_long" "-e" "2" "--fl" "0.0 0.05")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj-1-16-flux PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;39;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj3-1-16 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "qmc_j3_long.in.xml")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj3-1-16 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=16" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "quality_unknown;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "16" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;365;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;55;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj3-1-16-totenergy "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_j3_long" "-e" "2" "--le" "-31.913838 0.0008")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj3-1-16-totenergy PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj3-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;55;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj3-1-16-samples "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_j3_long" "-e" "2" "--ts" "2048000 0.0")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj3-1-16-samples PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj3-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;55;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
add_test(long-monoO_1x1x1_pp-vmc_sdj3-1-16-flux "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_scalars.py" "--ns" "3" "--series" "0" "-p" "qmc_j3_long" "-e" "2" "--fl" "0.0 0.27")
set_tests_properties(long-monoO_1x1x1_pp-vmc_sdj3-1-16-flux PROPERTIES  DEPENDS "long-monoO_1x1x1_pp-vmc_sdj3-1-16" LABELS "QMCPACK-checking-results;quality_unknown;unstable" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/monoO_1x1x1_pp/long-monoO_1x1x1_pp-vmc_sdj3-1-16" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;423;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;55;qmc_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/monoO_1x1x1_pp/CMakeLists.txt;0;")
