#!/usr/bin/env python3

import sys,os
sys.path.append(os.path.join(os.path.dirname(__file__), '../nexus/lib'))

if len(sys.argv)<2:
    print('Usage:\n{} <gamess-input-pp>'.format(executable_name))
    sys.exit(2)
#end if

from pseudopotential import GaussianPP
for filepath in sys.argv[1:]:
    path,filename = os.path.split(filepath)
    filename = filename.replace('.gms','').replace('.gamess','')+'.xml'
    pp = GaussianPP(filepath,format='gamess')
    pp.write(os.path.join(path,filename),format='qmcpack')
#end for

