#!/usr/bin/env python3

import sys,os
nexus_lib = os.path.join(os.path.dirname(__file__), '../nexus/lib')
sys.path.append(nexus_lib)
try:
    from pseudopotential import GaussianPP
except:
    print('Nexus must be installed to run this script.\nExpected Nexus library at {}'.format(nexus_lib))
    sys.exit(1)
#end try

executable_name = sys.argv[0]
if len(sys.argv)<2:
    print('Usage:\n{} <gamess-input-pp>'.format(executable_name))
    sys.exit(2)
#end if

from pseudopotential import GaussianPP
for filepath in sys.argv[1:]:
    path,filename = os.path.split(filepath)
    filename = filename.replace('.gms','').replace('.gamess','')+'.xml'
    pp = GaussianPP(filepath,format='gamess')
    pp.write(os.path.join(path,filename),format='qmcpack')
#end for

