$(ODIR)/ParticleBase.o: $(QMCDIR)/src/Particle/ParticleBase.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/ParticleBase.cpp -o $(ODIR)/ParticleBase.o
$(ODIR)/MCWalkerConfiguration.o: $(QMCDIR)/src/Particle/MCWalkerConfiguration.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/MCWalkerConfiguration.cpp -o $(ODIR)/MCWalkerConfiguration.o
$(ODIR)/DistanceTableData.o: $(QMCDIR)/src/Particle/DistanceTableData.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/DistanceTableData.cpp -o $(ODIR)/DistanceTableData.o
$(ODIR)/DistanceTable.o: $(QMCDIR)/src/Particle/DistanceTable.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/DistanceTable.cpp -o $(ODIR)/DistanceTable.o
