#//////////////////////////////////////////////////////////////////////////////////////
#// This file is distributed under the University of Illinois/NCSA Open Source License.
#// See LICENSE file in top directory for details.
#//
#// Copyright (c) 2016 Jeongnim Kim and QMCPACK developers.
#//
#// File developed by: Jeongnim Kim, jeongnim.kim@gmail.com, University of Illinois at Urbana-Champaign
#//                    Jeremy McMinnis, jmcminis@gmail.com, University of Illinois at Urbana-Champaign
#//
#// File created by: Jeongnim Kim, jeongnim.kim@gmail.com, University of Illinois at Urbana-Champaign
#//////////////////////////////////////////////////////////////////////////////////////
    
    



$(ODIR)/ParticleBase.o: $(QMCDIR)/src/Particle/ParticleBase.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/ParticleBase.cpp -o $(ODIR)/ParticleBase.o
$(ODIR)/MCWalkerConfiguration.o: $(QMCDIR)/src/Particle/MCWalkerConfiguration.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/MCWalkerConfiguration.cpp -o $(ODIR)/MCWalkerConfiguration.o
$(ODIR)/DistanceTableData.o: $(QMCDIR)/src/Particle/DistanceTableData.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/DistanceTableData.cpp -o $(ODIR)/DistanceTableData.o
$(ODIR)/DistanceTable.o: $(QMCDIR)/src/Particle/DistanceTable.cpp
	$(CXX) $(CXXFLAGSAPP) $(OHMMSINC) -c $(QMCDIR)/src/Particle/DistanceTable.cpp -o $(ODIR)/DistanceTable.o
