#ifndef QMCPLUSPLUS_AFQMC_WALKERCONFIG_HPP
#define QMCPLUSPLUS_AFQMC_WALKERCONFIG_HPP

// basic definitions used by walker set classes
enum LOAD_BALANCE_ALGORITHM { UNDEFINED_LOAD_BALANCE, SIMPLE, ASYNC };
enum BRANCHING_ALGORITHM { UNDEFINED_BRANCHING, PAIR, COMB, MIN_BRANCH, SERIAL_COMB };

#endif
