# Copyright 2020-2025 Alfredo A. Correa

image: debian:testing

workflow:
  auto_cancel:
    on_new_commit: interruptible

variables:
  GIT_SUBMODULE_STRATEGY: recursive

openmpi:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends ca-certificates libopenmpi-dev openmpi-bin cmake make g++ git libboost-serialization-dev
    - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
    - cd test
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --parallel 2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure

openmpi-g++-7:
  stage: build
  image: debian:oldoldstable  # default is gcc 8 as of Dec 2023
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends ca-certificates libopenmpi-dev openmpi-bin cmake make g++-7 git libboost-serialization-dev
    - apt-get -qq -y install wget
    - wget https://github.com/Kitware/CMake/releases/download/v3.27.0-rc3/cmake-3.27.0-rc3-linux-`uname -m`.sh --no-verbose
    - sh ./cmake-3.27.0-rc3-linux-`uname -m`.sh --skip-license --prefix=/usr
    - cmake --version
    - g++-7 --version
    - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
    - cd test
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - export MPI_ALLOW_RUN_AS_ROOT="--allow-run-as-root"
    - cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --parallel 2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure
  needs: ["openmpi"]

openmpi-clang:
  stage: build
  image: debian:testing
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends ca-certificates libopenmpi-dev openmpi-bin cmake make clang g++ git libstdc++-12-dev libboost-serialization-dev
    - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
    - cd test
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - clang++ --version
    - mpirun --version
    - CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --parallel 2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure
  needs: ["openmpi"]

openmpi-clang20:
  stage: build
  image: debian:stable
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends ca-certificates libopenmpi-dev openmpi-bin cmake make clang git libstdc++-12-dev libboost-serialization-dev
    - cd test
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - clang++ --version
    - mpirun --version
    - CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20
    - cmake --build . --parallel 2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure
  needs: ["openmpi-clang"]

openmpi-clang-tidy:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends ca-certificates libopenmpi-dev openmpi-bin clang libstdc++-12-dev clang-tidy cmake git make libboost-serialization-dev
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - clang++ --version
    - clang-tidy --version
    - CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CLANG_TIDY="clang-tidy"
    - make --jobs=2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure
  needs: ["openmpi-clang"]

openmpi-cppcheck:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin g++ libstdc++-12-dev ca-certificates cmake cppcheck git make libboost-serialization-dev pkg-config libfftw3-dev libfftw3-mpi-dev
    - mkdir build && cd build
    - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - g++ --version
    - cppcheck --version
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CPPCHECK="cppcheck;--force;--enable=all;--inline-suppr;--language=c++;--check-level=exhaustive;--suppress=missingIncludeSystem;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--std=c++17;--error-exitcode=666;-UEXCLUDE_CPPCHECK"
    - make --jobs=2 || make VERBOSE=1
    - OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 ctest --output-on-failure
  needs: ["openmpi"]

mpich-debug:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin g++ libstdc++-12-dev ca-certificates cmake cppcheck git make libboost-serialization-dev
    - cd test
    - mkdir build && cd build
    - export PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe 
    # - export MPI_OVERSUBSCRIBE="--oversubscribe"
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --parallel 2 || cmake --build . --verbose
    - ctest --output-on-failure
