# FFTW_INCLUDE_DIR = fftw3.h
# FFTW_LIBRARIES = libfftw3.a
# FFTW_FOUND = true if FFTW3 is found

set(Libfftw fftw3)
if(QMC_BUILD_STATIC)
  set(Libfftw libfftw3.a)
endif(QMC_BUILD_STATIC)

if(FFTW_INCLUDE_DIRS)
  find_path(FFTW_INCLUDE_DIR fftw3.h ${FFTW_INCLUDE_DIRS})
  find_library(FFTW_LIBRARIES ${Libfftw} ${FFTW_LIBRARY_DIRS})
else(FFTW_INCLUDE_DIRS)
  find_path(FFTW_INCLUDE_DIR fftw3.h ${FFTW_HOME}/include $ENV{FFTW_HOME}/include)
  find_library(FFTW_LIBRARIES ${Libfftw} ${FFTW_HOME}/lib $ENV{FFTW_HOME}/lib)
endif(FFTW_INCLUDE_DIRS)

set(FFTW_FOUND FALSE)
if(FFTW_INCLUDE_DIR AND FFTW_LIBRARIES)
  message(STATUS "FFTW_INCLUDE_DIR=${FFTW_INCLUDE_DIR}")
  message(STATUS "FFTW_LIBRARIES=${FFTW_LIBRARIES}")
  set(FFTW_FOUND TRUE)
  #create FFTW3 target
  add_library(Math::FFTW3 INTERFACE IMPORTED)
  set_target_properties(
    Math::FFTW3
    PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${FFTW_INCLUDE_DIR}" INTERFACE_COMPILE_DEFINITIONS "HAVE_LIBFFTW"
               INTERFACE_LINK_LIBRARIES "${FFTW_LIBRARIES}")
endif()

mark_as_advanced(FFTW_INCLUDE_DIR FFTW_LIBRARIES FFTW_FOUND)
