
INCLUDE("${qmcpack_SOURCE_DIR}/CMake/test_labels.cmake")

# Runs unit tests
FUNCTION( ADD_PYSCF_TEST TESTNAME TEST_BINARY WORKDIR TEST_INPUT)
    ADD_TEST( NAME ${TESTNAME} COMMAND ${TEST_BINARY} ${TEST_INPUT} )

    SET_TESTS_PROPERTIES( ${TESTNAME} PROPERTIES WORKING_DIRECTORY ${WORKDIR} )
    SET_PROPERTY( TEST ${TESTNAME} APPEND PROPERTY LABELS "converter" )
ENDFUNCTION()

FUNCTION( RUN_PYSCF_TEST BASE_NAME SRC_DIR TEST_INPUT_PREFIX TEST_NAME)
    SET( ${TEST_NAME} ${BASE_NAME} PARENT_SCOPE)
    SET( MY_WORKDIR ${CMAKE_CURRENT_BINARY_DIR}/${BASE_NAME} )
    MESSAGE_VERBOSE("Adding test ${BASE_NAME}")
    COPY_DIRECTORY( "${SRC_DIR}" "${MY_WORKDIR}" )
    ADD_PYSCF_TEST(${BASE_NAME} python ${MY_WORKDIR} ${TEST_INPUT_PREFIX}.py )
ENDFUNCTION()

FUNCTION( SOFTLINK_H5 SOURCE TARGET PREFIX FILENAME TEST_NAME)
    SET(${TEST_NAME} "LINK_${SOURCE}_TO_${TARGET}" PARENT_SCOPE)
    ADD_TEST( NAME LINK_${SOURCE}_TO_${TARGET} COMMAND ${qmcpack_SOURCE_DIR}/tests/scripts/clean_and_link_h5.sh ${SOURCE}/${PREFIX}.h5 ${SOURCE}-${TARGET}/${FILENAME} )
    SET_TESTS_PROPERTIES(LINK_${SOURCE}_TO_${TARGET} PROPERTIES DEPENDS ${SOURCE})
    SET_PROPERTY( TEST LINK_${SOURCE}_TO_${TARGET} APPEND PROPERTY LABELS "converter" )
ENDFUNCTION()
