# CMake generated Testfile for 
# Source directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae
# Build directory: /gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(short-bccH_3x3x3_ae-deriv-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "deriv.xml")
set_tests_properties(short-bccH_3x3x3_ae-deriv-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "bug;poor_test;abort;check_fail;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;583;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;2;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-deriv-1-1-check "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_deriv.py")
set_tests_properties(short-bccH_3x3x3_ae-deriv-1-1-check PROPERTIES  DEPENDS "short-bccH_3x3x3_ae-deriv-1-1" LABELS "unstable;bug;poor_test;abort;check_fail" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;610;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;2;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-grad_lap-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "grad_lap.xml")
set_tests_properties(short-bccH_3x3x3_ae-grad_lap-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "bug;poor_test;abort;check_fail;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-grad_lap-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;583;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;5;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-grad_lap-1-1-check "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_grad_lap.py")
set_tests_properties(short-bccH_3x3x3_ae-grad_lap-1-1-check PROPERTIES  DEPENDS "short-bccH_3x3x3_ae-grad_lap-1-1" LABELS "unstable;bug;poor_test;abort;check_fail" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-grad_lap-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;610;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;5;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-gamma-deriv-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "gamma_deriv.xml")
set_tests_properties(short-bccH_3x3x3_ae-gamma-deriv-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "bug;poor_test;abort;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-gamma-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;583;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;8;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-gamma-deriv-1-1-check "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_deriv.py")
set_tests_properties(short-bccH_3x3x3_ae-gamma-deriv-1-1-check PROPERTIES  DEPENDS "short-bccH_3x3x3_ae-gamma-deriv-1-1" LABELS "unstable;bug;poor_test;abort" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-gamma-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;610;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;8;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-not_orth-deriv-1-1 "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/intel-2021.1.2/openmpi-4.1.2-awpydu2boorwxkfkfgtkgilngfsokjy4/bin/mpiexec" "-n" "1" "--bind-to" "none" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/bin/qmcpack_complex" "not-orth_deriv.xml")
set_tests_properties(short-bccH_3x3x3_ae-not_orth-deriv-1-1 PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" FAIL_REGULAR_EXPRESSION "ERROR" LABELS "bug;poor_test;abort;QMCPACK" PASS_REGULAR_EXPRESSION "QMCPACK execution completed successfully" PROCESSORS "1" PROCESSOR_AFFINITY "TRUE" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-not_orth-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;145;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;234;run_qmc_app_no_copy;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;583;run_qmc_app;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;11;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
add_test(short-bccH_3x3x3_ae-not_orth-deriv-1-1-check "/projects/cde/v3/cee/spack/opt/spack/linux-rhel7-x86_64/gcc-10.3.0/anaconda3-2021.05-hzr5w5v54sh3moi43gtl2fzdffebm2tf/bin/python3.8" "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/scripts/check_deriv.py")
set_tests_properties(short-bccH_3x3x3_ae-not_orth-deriv-1-1-check PROPERTIES  DEPENDS "short-bccH_3x3x3_ae-not_orth-deriv-1-1" LABELS "unstable;bug;poor_test;abort" WORKING_DIRECTORY "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/build-complex-soa-fp-cee/tests/solids/bccH_3x3x3_ae/short-bccH_3x3x3_ae-not_orth-deriv-1-1" _BACKTRACE_TRIPLES "/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/CMake/macros.cmake;610;add_test;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;11;simple_run_and_check;/gpfs/rclay/qmcpack_worktree/complex_orb_opt_fix/tests/solids/bccH_3x3x3_ae/CMakeLists.txt;0;")
