# # Copyright 2020-2026 Alfredo A. Correa

image: debian:stable

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  CMAKE_GENERATOR: "Unix Makefiles"

g++:  # debian-stable: default is gcc 14.2.0 as of Dec 2025
  stage: build
  interruptible: false
  # tags:
  #   - non-shared
  #   - docker
  script:
    - apt-get -qq update
    - apt-get -qq install --no-install-recommends -y --quiet ca-certificates python3 ninja-build cmake gcc g++ git make libboost-timer-dev libboost-serialization-dev libblas-dev liblapack-dev libfftw3-dev pkg-config
    - g++ --version
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3 -ftrivial-auto-var-init=zero -fPIE  -pie  -Wl,-z,relro,-z,now -fstack-protector-strong -fstack-clash-protection"
    - cmake --build . || cmake --build . --verbose
    - ctest --parallel 2 || ctest --verbose --rerun-failed --output-on-failure

clang++:
  stage: build
  # tags:
  #   - non-shared
  #   - docker
  interruptible: false
  script:
    - apt-get -qq update
    - apt-get -qq install --no-install-recommends -y --quiet ca-certificates clang ninja-build cmake git python3 make libboost-timer-dev libboost-serialization-dev libblas-dev libfftw3-dev liblapack-dev pkg-config
    - mkdir build && cd build
    - clang++ --version
    - CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1"
    - cmake --build . || cmake --build . --parallel 1 --verbose
    - ctest --parallel 2 || ctest --verbose --rerun-failed --output-on-failure

clang++-latest libc++ format:
  stage: build
  image: debian:latest
  # tags:
  #   - non-shared
  #   - docker
  interruptible: true
  script:
    - apt-get -qq update
    - apt-get -qq install --no-install-recommends -y --quiet ca-certificates git clang clang-format ninja-build cmake make libboost-timer-dev libboost-serialization-dev libblas-dev libc++-dev libc++abi-dev libfftw3-dev liblapack-dev pkg-config tar wget
    - mkdir build && cd build
    - clang++ --version
    - CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-stdlib=libc++ -DBOOST_NO_CXX98_FUNCTION_BASE -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG"
    - cmake --build . || cmake --build . --parallel 1 --verbose
    - ctest -j 2 --output-on-failure
    - cd ..
    - clang-format --version
    - clang-format --dry-run -Werror test/*.cpp include/**/*.hpp || echo "errors in formatting"
  needs: ["clang++"]
